apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-business-projects-openproject-secrets
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: k0s-cntrl
            url: https://10.1.1.40:443
            environment: 'prod'
  template:
    metadata:
      name: '{{cluster}}-business-projects-openproject-{{environment}}-secrets'
    spec:
      project: core
      syncPolicy:
        automated: {}

      source:
        path: Projects/OpenProjectExtraChart
        repoURL: https://gitlab.git.writemy.codes/KJDev/core-business.git
        targetRevision: main
        helm:
          parameters:
            - name: secretSuffix
              value: '{{ environment }}'

      destination:
        server: '{{url}}'
        namespace: core-prod
