apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: '{{ .Values.donetick.jwtSecret.generatorName }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  length: 64
  digits: 0
  symbols: 0
  allowRepeat: true
  encoding: 'hex'
  secretKeys:
    - 'JWT_SECRET'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ .Values.donetick.jwtSecret.secretName }}-generate'
  annotations:
    argocd.argoproj.io/sync-wave: '-9'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: '{{ .Values.donetick.jwtSecret.secretName }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: 'Password'
          name: '{{ .Values.donetick.jwtSecret.generatorName }}'
