apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ .Release.Name }}
spec:
  requestBuffer:
    limit: 100Mi
  timeout:
    http:
      requestTimeout: 60s
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ .Release.Name }}