{{- if and .Values.nextcloud.enabled .Values.nextcloudRedis.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.nextcloudRedis.secretName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  refreshInterval: {{ .Values.nextcloudRedis.refreshInterval | quote }}
  secretStoreRef:
    kind: {{ .Values.nextcloudRedis.secretStoreRef.kind | quote }}
    name: {{ .Values.nextcloudRedis.secretStoreRef.name | quote }}

  target:
    name: {{ .Values.nextcloudRedis.secretName | quote }}
    creationPolicy: 'Owner'

  data:
    - secretKey: 'password'
      remoteRef:
        key: {{ default (printf "Storage/DragonFly/CoRE/%s/%s/%s/Creds" .Values.region .Values.datacenter .Values.cluster.name) .Values.nextcloudRedis.remoteRef.key | quote }}
        property: {{ .Values.nextcloudRedis.remoteRef.property | quote }}
{{- end }}
