apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: business-office-nextcloud-keys-prod-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-office-nextcloud-keys-prod

  data:
    - secretKey: PasswordSalt
      remoteRef:
        key: Nextcloud/Encryption
        property: PasswordSalt

    - secretKey: Secret
      remoteRef:
        key: Nextcloud/Encryption
        property: Secret

    - secretKey: AdminUser
      remoteRef:
        key: Nextcloud/Admin
        property: Username

    - secretKey: AdminPassword
      remoteRef:
        key: Nextcloud/Admin
        property: Password

    - secretKey: TOKEN
      remoteRef:
        key: Nextcloud/Encryption
        property: Token

