{{- if .Values.nextcloud.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: office-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Values.gateway.namespace }}
      name: {{ .Values.gateway.name }}
      sectionName: {{ .Values.gateway.sectionName }}

  hostnames:
    - 'office.mylogin.space'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/carddav

        - path:
            type: PathPrefix
            value: /.well-known/caldav

      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /nextcloud/remote.php/dav
            statusCode: 301


    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/webfinger

      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /nextcloud/index.php/.well-known/webfinger
            statusCode: 301


    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/nodeinfo

      timeouts:
        request: 120s
        backendRequest: 100s

      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /nextcloud/index.php/.well-known/nodeinfo 
            statusCode: 301

    - matches:
        - path:
            type: RegularExpression
            value: .*\.(css|js|mjs|svg|gif|ico|jpg|png|webp|wasm|tflite|map|ogg|flac|mp4|webm)

      filters:
        - type: ResponseHeaderModifier
          responseHeaderModifier:
            add:
              - name: Cache-Control
                value: public, max-age 86400

    - backendRefs:
        - group: ''
          kind: Service
          name: {{ template "nextcloud.fullname" $.Subcharts.nextcloud }}
          port: 8080
          weight: 1

      timeouts:
        request: 120s
        backendRequest: 100s
{{- end }}