{{- if .Values.nextcloud.enabled }}

apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ template "nextcloud.fullname" $.Subcharts.nextcloud }}

spec:
  name: NextCloud

  psql:
    enabled: true

    crossplane:
      crossplaneProvider: psql-main
      terraformProvider: psql

  s3:
    enabled: true

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ template "nextcloud.fullname" $.Subcharts.nextcloud }}-creds
{{- end }}