{{- if .Values.nextcloud.enabled }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: nextcloud-core-{{ .Values.env }}

spec:
  name: NextCloud {{ .Values.region }}

  psql:
    enabled: true

    crossplane:
      crossplaneProvider: psql-main
      terraformProvider: psql

  s3:
    enabled: true

    createCredentials: true

    crossplane:
      terraformProvider: s3-yvr-home1-core
      crossplaneProvider: s3-yvr-home1-core

    writeCredentialsSecretRef:
      name: office-nextcloud-s3-creds
      namespace: {{ .Release.Namespace }}

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: office-nextcloud-creds
{{- end }}