{{- if .Values.nextcloud.enabled }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ template "nextcloud.fullname" $.Subcharts.nextcloud }}

spec:
  name: NextCloud {{ .Values.region }}

  psql:
    enabled: true

    crossplane:
      crossplaneProvider: psql-main
      terraformProvider: psql

  s3:
    enabled: true

    createCredentials: true

    crossplane:
      terraformProvider: s3-yvr-home1-core
      crossplaneProvider: s3-yvr-home1-core

    writeCredentialsSecretRef:
      name: {{ include "loki.fullname" $.Subcharts.loki }}-s3-creds
      namespace: {{ .Release.Namespace }}

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ template "nextcloud.fullname" $.Subcharts.nextcloud }}-creds
{{- end }}