apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: business-office-nextcloud-s3-prod-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-office-nextcloud-s3-prod

  data:
    - secretKey: S3Bucket
      remoteRef:
        key: Nextcloud/S3
        property: Bucket

    - secretKey: S3AccessKey
      remoteRef:
        key: Nextcloud/S3
        property: AccessKey
      
    - secretKey: S3SecretKey
      remoteRef:
        key: Nextcloud/S3
        property: SecretKey
