{{- if and .Values.nextcloud.enabled .Values.nextcloudS3Credentials.enabled }}
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.nextcloudS3Credentials.providerConfigRef | quote }}
spec:
  pluginCache: true
  configuration: | # hcl
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-office-nextcloud-s3-session"
        namespace         = {{ .Release.Namespace | quote }}
        in_cluster_config = true
      }

      required_providers {
        minio = {
          source  = "aminueza/minio"
          version = {{ .Values.nextcloudS3Credentials.terraformProviderVersion | quote }}
        }
      }
    }
{{- end }}
