{{- if .Values.nextcloud.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'nextcloud-background-workers'
  labels:
    app.kubernetes.io/name: 'nextcloud'
    app.kubernetes.io/component: 'nextcloud-task-worker'
spec:
  replicas: 1
  strategy:
    type: 'Recreate'
  selector:
    matchLabels:
      app.kubernetes.io/name: 'nextcloud'
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
      app.kubernetes.io/component: 'nextcloud-task-worker'
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'nextcloud'
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/component: 'nextcloud-task-worker'
    spec:
      {{- include "office.nextcloud.background.commonPodSpec" . | nindent 6 }}
      containers:
        - name: 'nextcloud-task-worker'
          image: {{ include "nextcloud.image" .Subcharts.nextcloud | quote }}
          imagePullPolicy: {{ .Values.nextcloud.image.pullPolicy | quote }}
          workingDir: '/var/www/html'
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ['ALL']
            runAsNonRoot: true
            runAsUser: 82
          command:
            - '/bin/sh'
            - '-ec'
            - 'while true; do php /var/www/html/occ taskprocessing:worker -v -t 60; done'
          env:
            - name: PHP_INI_SCAN_DIR
              value: '/usr/local/etc/php/conf.d:/tmp/php-conf.d'
            {{- include "nextcloud.env" .Subcharts.nextcloud | nindent 12 }}
          resources:
            {{- toYaml .Subcharts.nextcloud.Values.resources | nindent 12 }}
          volumeMounts:
            {{- include "nextcloud.volumeMounts" .Subcharts.nextcloud | nindent 12 }}
{{- end }}
