{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-asterisk

  labels:
    app: {{ $fullName }}-asterisk

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ $fullName }}-asterisk

  template:
    metadata:
      labels:
        app: {{ $fullName }}-asterisk
        logs: loki-myloginspace

    spec:
      containers:
        - image: kristianfoss/newasterisk:core
          imagePullPolicy: Always
          name: asterisk

          ports:
            - name: tcp-sip
              containerPort: 5060
              protocol: TCP

            - name: udp-sip
              containerPort: 5060
              protocol: TCP

            - name: tls-sips
              containerPort: 5061
              protocol: TCP

        {{ range untilStep (.Values.asterisk.rtp.min|int) (.Values.asterisk.rtp.max|int) 1 }}
            - name: 'udp-{{ . }}'
              containerPort: {{ . }}
              protocol: UDP

            - name: 'tcp-{{ . }}'
              containerPort: {{ . }}
              protocol: TCP
        {{ end }}


          # env:
          #   - name: CONTEXTUALISE_SETTINGS
          #     value: /src/contextualise/settings.cfg

          volumeMounts:
            - name: asterisk-secret-config
              subPath: pjsip.conf
              mountPath: /etc/asterisk/pjsip.conf

            - name: asterisk-config
              subPath: rtp.conf
              mountPath: /etc/asterisk/rtp.conf

            - name: asterisk-config
              subPath: extensions.conf
              mountPath: /etc/asterisk/extensions.conf

            - name: asterisk-config
              subPath: logger.conf
              mountPath: /etc/asterisk/logger.conf

            - name: asterisk-config
              subPath: modules.conf
              mountPath: /etc/asterisk/modules.conf

            - name: asterisk-config
              subPath: asterisk.conf
              mountPath: /etc/asterisk/asterisk.conf

      volumes:
        - name: asterisk-config
          configMap:
            name: {{ $fullName }}-asterisk-configs
            items:
              - key: rtp.conf
                path: rtp.conf

              - key: extensions.conf
                path: extensions.conf

              - key: logger.conf
                path: logger.conf

              - key: asterisk.conf
                path: asterisk.conf

              - key: modules.conf
                path: modules.conf

        - name: asterisk-secret-config
          secret:
            secretName: {{ $fullName }}-asterisk-sip-config
            items:
              - key: pjsip.conf
                path: pjsip.conf

        - name: data-volume
          emptyDir: {}
