{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: asterisk

spec:
  selector:
    app: {{ $fullName }}-asterisk

  ports:
{{- range untilStep (.Values.asterisk.rtp.min|int) (.Values.asterisk.rtp.max|int) 1 }}
    - port: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: 'udp-{{ . }}'

{{ end }}



  publishNotReadyAddresses: true
  loadBalancerIP: 10.1.1.5
  externalIPs:
    - 66.165.222.101
  type: LoadBalancer
