apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-avoip-ejabberd-cfg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: corevault-rootsecrets

  target:
    name: business-avoip-ejabberd-cfg-tpl
    template:
      engineVersion: v2

      templateFrom:
        - configMap:
            name: business-avoip-ejabberd-cfg-tpl
            # here you define the keys that should be used as template
            items:
              - key: eJabberD.yaml
  data:
    #
    # General AAA
    #
    - secretKey: Username
      remoteRef:
        key: AVoIP/eJabberD/LDAP
        property: Username

    - secretKey: Password
      remoteRef:
        key: AVoIP/eJabberD/LDAP
        property: Password
