{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-freeswitch-rtp

  annotations:
    io.cilium/lb-ipam-sharing-key: main-gw
    metallb.universe.tf/address-pool: pub-pool
    metallb.universe.tf/allow-shared-ip: main-gw
    metallb.universe.tf/ip-allocated-from-pool: pub-pool
spec:
  type: LoadBalancer

  ports:
    - name: sip-udp
      port: 5060
      protocol: UDP
      targetPort: 5080

    - name: sip-tcp
      port: 5060
      protocol: TCP
      targetPort: 5080


{{- range untilStep (.Values.freeswitch.rtp.min|int) (.Values.freeswitch.rtp.max|int) 1 }}
    - port: {{ . }}
      nodeport: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: 'udp-{{ . }}'
{{ end }}

  selector:
    app: {{ $fullName }}-freeswitch

