{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-freeswitch

  labels:
    app: {{ $fullName }}-freeswitch

spec:
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ $fullName }}-freeswitch

  template:
    metadata:
      labels:
        app: {{ $fullName }}-freeswitch
        logs: loki-myloginspace

    spec:
      containers:
        - image: kristianfjones/freeswitch:core
          imagePullPolicy: Always
          name: freeswitch

          args:
            - -c

          ports:
            - name: tcp-sip
              containerPort: 5060
              protocol: TCP

            - name: udp-sip
              containerPort: 5060
              protocol: TCP

            - name: tls-sips
              containerPort: 5061
              protocol: TCP

          # env:
          #   - name: CONTEXTUALISE_SETTINGS
          #     value: /src/contextualise/settings.cfg

          volumeMounts:
            - name: freeswitch-config
              subPath: freeswitch.xml
              mountPath: /etc/freeswitch/freeswitch.xml

            - name: freeswitch-config
              subPath: extensions.conf
              mountPath: /etc/freeswitch/extensions.conf

            #
            # SIP
            #
            - name: freeswitch-sip-config
              subPath: external.xml
              mountPath: /etc/freeswitch/sip_profiles/external.xml

            - name: freeswitch-sip-config
              subPath: asterisk.xml
              mountPath: /etc/freeswitch/sip_profiles/asterisk.xml

            #
            # Dialplan
            #

            - name: freeswitch-dialplan-config
              subPath: default.xml
              mountPath: /etc/freeswitch/dialplan/default.xml

            
            #
            # Modules
            #
            - name: freeswitch-misc-config
              subPath: modules.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/modules.conf.xml

            - name: freeswitch-misc-config
              subPath: switch.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/switch.conf.xml

            - name: freeswitch-misc-config
              subPath: logfile.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/logfile.conf.xml

            - name: freeswitch-misc-config
              subPath: acl.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/acl.conf.xml

            - name: freeswitch-misc-config
              subPath: sofia.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/sofia.conf.xml

      volumes:
        - name: freeswitch-config
          configMap:
            name: {{ $fullName }}-freeswitch-configs
            items:
              - key: freeswitch.xml
                path: freeswitch.xml

              - key: extensions.conf
                path: extensions.conf
            
        - name: freeswitch-misc-config
          configMap:
            name: {{ $fullName }}-freeswitch-misc-configs
            items:
              - key: modules.conf.xml
                path: modules.conf.xml

              - key: console.conf.xml
                path: console.conf.xml

              - key: acl.conf.xml
                path: acl.conf.xml

              - key: switch.conf.xml
                path: switch.conf.xml

              - key: console.conf.xml
                path: console.conf.xml

              - key: logfile.conf.xml
                path: logfile.conf.xml

              - key: sofia.conf.xml
                path: sofia.conf.xml
          
          


        - name: freeswitch-sip-config
          configMap:
            name: {{ $fullName }}-freeswitch-sip-configs
            items:
              - key: external.xml
                path: external.xml

              - key: asterisk.xml
                path: asterisk.xml

        - name: freeswitch-dialplan-config
          configMap:
            name: {{ $fullName }}-freeswitch-dialplan-configs
            items:
              - key: default.xml
                path: default.xml

        - name: data-volume
          emptyDir: {}
