{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-freeswitch-misc-configs

data:
  modules.conf.xml: |
    <configuration name="modules.conf" description="Modules">
      <modules>
        <!-- Loggers (I'd load these first) -->
        <load module="mod_console"/>
        <!-- <load module="mod_graylog2"/> -->
        <load module="mod_logfile"/>
        <!-- <load module="mod_syslog"/> -->

        <!--<load module="mod_yaml"/>-->

        <!-- Multi-Faceted -->
        <!-- mod_enum is a dialplan interface, an application interface and an api command interface -->
        <load module="mod_enum"/>

        <!-- XML Interfaces -->
        <!-- <load module="mod_xml_rpc"/> -->
        <!-- <load module="mod_xml_curl"/> -->
        <!-- <load module="mod_xml_cdr"/> -->
        <!-- <load module="mod_xml_radius"/> -->
        <!-- <load module="mod_xml_scgi"/> -->

        <!-- Event Handlers -->
        <!-- <load module="mod_amqp"/> -->
        <load module="mod_cdr_csv"/>
        <!-- <load module="mod_cdr_sqlite"/> -->
        <!-- <load module="mod_event_multicast"/> -->
        <load module="mod_event_socket"/>
        <!-- <load module="mod_event_zmq"/> -->
        <!-- <load module="mod_zeroconf"/> -->
        <!-- <load module="mod_erlang_event"/> -->
        <!-- <load module="mod_smpp"/> -->
        <!-- <load module="mod_snmp"/> -->

        <!-- Directory Interfaces -->
        <!-- <load module="mod_ldap"/> -->

        <!-- Endpoints -->
        <!-- <load module="mod_dingaling"/> -->
        <!-- <load module="mod_portaudio"/> -->
        <!-- <load module="mod_alsa"/> -->
        <load module="mod_sofia"/>
        <load module="mod_loopback"/>
        <!-- <load module="mod_woomera"/> -->
        <!-- <load module="mod_freetdm"/> -->
        <!-- <load module="mod_unicall"/> -->
        <!-- <load module="mod_skinny"/> -->
        <!-- <load module="mod_khomp"/>   -->
        <load module="mod_rtc"/>
        <!-- <load module="mod_rtmp"/>   -->
        <load module="mod_verto"/>

        <!-- Applications -->
        <load module="mod_signalwire"/>
        <load module="mod_commands"/>
        <load module="mod_conference"/>
        <!-- <load module="mod_curl"/> -->
        <load module="mod_db"/>
        <load module="mod_dptools"/>
        <load module="mod_expr"/>
        <load module="mod_fifo"/>
        <load module="mod_hash"/>
        <!--<load module="mod_mongo"/> -->
        <load module="mod_voicemail"/>
        <!--<load module="mod_directory"/>-->
        <!--<load module="mod_distributor"/>-->
        <!--<load module="mod_lcr"/>-->
        <!--<load module="mod_easyroute"/>-->
        <load module="mod_esf"/>
        <load module="mod_fsv"/>
        <!--<load module="mod_cluechoo"/>-->
        <load module="mod_valet_parking"/>
        <!--<load module="mod_fsk"/>-->
        <!--<load module="mod_spy"/>-->
        <!--<load module="mod_sms"/>-->
        <!--<load module="mod_sms_flowroute"/>-->
        <!--<load module="mod_smpp"/>-->
        <!--<load module="mod_random"/>-->
        <load module="mod_httapi"/>
        <!--<load module="mod_translate"/>-->

        <!-- SNOM Module -->
        <!--<load module="mod_snom"/>-->

        <!-- This one only works on Linux for now -->
        <!--<load module="mod_ladspa"/>-->

        <!-- Dialplan Interfaces -->
        <!-- <load module="mod_dialplan_directory"/> -->
        <load module="mod_dialplan_xml"/>
        <load module="mod_dialplan_asterisk"/>

        <!-- Codec Interfaces -->
        <load module="mod_spandsp"/>
        <load module="mod_g723_1"/>
        <load module="mod_g729"/>
        <load module="mod_amr"/>
        <!--<load module="mod_ilbc"/>-->
        <!--<load module="mod_h26x"/>-->
        <load module="mod_b64"/>
        <!--<load module="mod_siren"/>-->
        <!--<load module="mod_isac"/>-->
        <load module="mod_opus"/>

        <!-- File Format Interfaces -->
        <load module="mod_av"/>
        <load module="mod_sndfile"/>
        <load module="mod_native_file"/>
        <!--<load module="mod_opusfile"/>-->
        <load module="mod_png"/>
        <!-- <load module="mod_shell_stream"/> -->
        <!--For icecast/mp3 streams/files-->
        <!--<load module="mod_shout"/>-->
        <!--For local streams (play all the files in a directory)-->
        <load module="mod_local_stream"/>
        <load module="mod_tone_stream"/>

        <!-- Timers -->
        <!-- <load module="mod_timerfd"/> -->
        <!-- <load module="mod_posix_timer"/> -->

        <!-- Languages -->
        <!-- <load module="mod_v8"/> -->
        <!-- <load module="mod_perl"/> -->
        <!-- <load module="mod_python"/> -->
        <!-- <load module="mod_python3"/> -->
        <!-- <load module="mod_java"/> -->
        <load module="mod_lua"/>

        <!-- ASR /TTS -->
        <!-- <load module="mod_flite"/> -->
        <!-- <load module="mod_pocketsphinx"/> -->
        <!-- <load module="mod_cepstral"/> -->
        <!-- <load module="mod_tts_commandline"/> -->
        <!-- <load module="mod_rss"/> -->

        <!-- Say -->
        <load module="mod_say_en"/>
        <!-- <load module="mod_say_ru"/> -->
        <!-- <load module="mod_say_zh"/> -->
        <!-- <load module="mod_say_sv"/> -->

        <!-- Third party modules -->
        <!--<load module="mod_nibblebill"/>-->
        <!--<load module="mod_callcenter"/>-->

      </modules>
    </configuration>

  console.conf.xml: |
    <configuration name="console.conf" description="Console Logger">
      <!-- pick a file name, a function name or 'all' -->
      <!-- map as many as you need for specific debugging -->
      <mappings>
        <!-- 
          name can be a file name, function name or 'all' 
          value is one or more of debug,info,notice,warning,err,crit,alert,all
          See examples below
          The following map is the default, which is all debug levels enabled:
          <map name="all" value="debug,info,notice,warning,err,crit,alert"/>
          Example: the following turns on debugging for error and critical levels only
          <map name="all" value="err,crit"/>
          NOTE: using map name="all" will override any other settings!  If you 
                want a more specific set of console messages then you will need
                to specify which files and/or functions you want to have debug
                messages.  One option is to turn on just the more critical 
                messages with map name="all", then specify the other types of 
                console messages you want to see for various files and functions.
          Example: turn on ERROR, CRIT, ALERT for all modules, then specify other
                  levels for various modules and functions
            <map name="all" value="err,crit,alert"/>
            <map name="switch_loadable_module_process" value="all"/>
            <map name="mod_local_stream.c" value="warning,debug"/>
            <map name="mod_sndfile.c" value="warning,info,debug"/>
        -->
        <map name="all" value="console,debug,info,notice,warning,err,crit,alert"/>
        
        <!--
          You can use or modify this sample set of mappings.  It turns on higher
          level messages for all modules and then specifies extra lower level
          messages for freetdm, Sofia, and switch core messages.
          
        <map name="all"                         value="warning,err,crit,alert"/>
        <map name="zap_analog.c"                value="all"/>
        <map name="zap_io.c"                    value="all"/>
        <map name="zap_isdn.c"                  value="all"/>
        <map name="zap_zt.c"                    value="all"/>
        <map name="mod_freetdm"                 value="all"/>
        <map name="sofia.c"                     value="notice"/>
        <map name="switch_core_state_machine.c" value="all"/>      
        
        -->
      </mappings>
      <settings>
        <!-- comment or set to false for no color logging -->
        <param name="colorize" value="true"/>
        <param name="loglevel" value="$${console_loglevel}"/>
      </settings>
    </configuration>

  acl.conf.xml: |
    <configuration name="acl.conf" description="Network Lists">
      <network-lists>
        <!--
      These ACL's are automatically created on startup.
      rfc1918.auto  - RFC1918 Space
      nat.auto      - RFC1918 Excluding your local lan.
      localnet.auto - ACL for your local lan.
      loopback.auto - ACL for your local lan.
        -->

        <list name="lan" default="allow">
          <node type="deny" cidr="192.168.42.0/24"/>
          <node type="allow" cidr="192.168.42.42/32"/>
        </list>

        <!--
      This will traverse the directory adding all users
      with the cidr= tag to this ACL, when this ACL matches
      the users variables and params apply as if they
      digest authenticated.
        -->
        <list name="domains" default="deny">
          <!-- domain= is special it scans the domain from the directory to build the ACL -->
          <node type="allow" domain="$${domain}"/>
          <!-- use cidr= if you wish to allow ip ranges to this domains acl. -->
          <!-- <node type="allow" cidr="192.168.0.0/24"/> -->
        </list>

        <list name="asterisk" default="deny">
          <node type="allow" cidr="10.0.0.0/8"/>
        </list>
      </network-lists>
    </configuration>