{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-freeswitch

  labels:
    app.kubernetes.io/name: {{ $fullName }}-freeswitch

spec:
  replicas: 1
  revisionHistoryLimit: 3

  minReadySeconds: 30

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $fullName }}-freeswitch

  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $fullName }}-freeswitch
        logs: loki-myloginspace

    spec:
      containers:
        - image: dheaps/freeswitch:full
          imagePullPolicy: Always
          name: freeswitch

          ports:
            - name: udp-sip
              containerPort: 5060
              protocol: UDP

            - name: tcp-sip
              containerPort: 5060
              protocol: TCP

            - name: tls-sips
              containerPort: 5061
              protocol: TCP


            - name: udp-sipext
              containerPort: 5080
              protocol: UDP

            - name: tcp-sipext
              containerPort: 5080
              protocol: TCP

            - name: tls-sipext
              containerPort: 5081
              protocol: TCP

          env:
            - name: LDAP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-aaa
                  key: username

            - name: LDAP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $fullName }}-aaa
                  key: password

            - name: SOUND_TYPES
              value: 'music:en-us-callie'

            - name: SOUND_RATES
              value: '8000:16000'

          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - NET_ADMIN
                - NET_RAW
                - NET_BROADCAST
                - SYS_NICE
                - SYS_RESOURCE

          volumeMounts:
            #
            # Main Configs
            #
            - mountPath: /etc/freeswitch
              name: data-volume

            - name: freeswitch-config
              subPath: freeswitch.xml
              mountpath: /usr/share/freeswitch/conf/vanilla/freeswitch.xml

            - name: freeswitch-config
              subPath: vars.xml
              mountPath: /etc/freeswitch/vars.xml

            - name: freeswitch-config
              subPath: extensions.conf
              mountPath: /etc/freeswitch/extensions.conf

            #
            # Modules
            #
            - name: freeswitch-sms-config
              subPath: sms_flowroute.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/sms_flowroute.conf.xml

            - name: freeswitch-misc-config
              subPath: verto.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/verto.conf.xml

            - name: freeswitch-misc-config
              subPath: opus.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/opus.conf.xml


            - name: freeswitch-misc-config
              subPath: opal.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/opal.conf.xml

            - name: freeswitch-misc-config
              subPath: alsa.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/alsa.conf.xml

            - name: freeswitch-misc-config
              subPath: fifo.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/fifo.conf.xml

            - name: freeswitch-misc-config
              subPath: local_stream.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/local_stream.conf.xml


            - name: freeswitch-misc-config
              subPath: modules.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/modules.conf.xml

            - name: freeswitch-misc-config
              subPath: ivr.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/ivr.conf.xml

            - name: freeswitch-misc-config
              subPath: switch.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/switch.conf.xml

            - name: freeswitch-misc-config
              subPath: logfile.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/logfile.conf.xml

            - name: freeswitch-misc-config
              subPath: acl.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/acl.conf.xml

            - name: freeswitch-misc-config
              subPath: sofia.conf.xml
              mountPath: /etc/freeswitch/autoload_configs/sofia.conf.xml

            #
            # IVRs
            #

            - name: freeswitch-ivr-config
              subPath: demo-ivr.xml
              mountPath: /etc/freeswitch/ivr_menus/demo-ivr.xml

            #
            # TLS
            #

            - name: freeswitch-tls-certs
              subPath: agent.pem
              mountPath: /etc/freeswitch/tls/agent.pem

            - name: freeswitch-tls-certs
              subPath: tls.crt
              mountPath: /etc/freeswitch/tls/cafile.pem

            #
            # SIP
            #
            - name: freeswitch-sip-config
              subPath: external.xml
              mountPath: /etc/freeswitch/sip_profiles/external.xml

            - name: freeswitch-sip-config
              subPath: asterisk.xml
              mountPath: /etc/freeswitch/sip_profiles/asterisk.xml

            - name: freeswitch-upstream-config
              subPath: flowroute.xml
              mountPath: /etc/freeswitch/sip_profiles/external/flowroute.xml

            #
            # Dialplan
            #

            - name: freeswitch-dialplan-config
              subPath: default.xml
              mountPath: /etc/freeswitch/dialplan/default.xml

            - name: freeswitch-dialplan-config
              subPath: public.xml
              mountPath: /etc/freeswitch/dialplan/public.xml
            


      securityContext:
        fsGroup: 499
        runAsGroup: 499
        runAsUser: 0

      volumes:
        #
        # Main Config
        #

        - name: freeswitch-config
          configMap:
            name: {{ $fullName }}-freeswitch-configs
            items:
              - key: freeswitch.xml
                path: freeswitch.xml

              - key: extensions.conf
                path: extensions.conf

              - key: vars.xml
                path: vars.xml

        #
        # Module Autoload Configs
        #
        - name: freeswitch-misc-config
          configMap:
            name: {{ $fullName }}-freeswitch-misc-configs
            items:
              - key: opus.conf.xml
                path: opus.conf.xml

              - key: opal.conf.xml
                path: opal.conf.xml

              - key: verto.conf.xml
                path: verto.conf.xml

              - key: alsa.conf.xml
                path: alsa.conf.xml

              - key: fifo.conf.xml
                path: fifo.conf.xml

              - key: local_stream.conf.xml
                path: local_stream.conf.xml

              - key: modules.conf.xml
                path: modules.conf.xml

              - key: ivr.conf.xml
                path: ivr.conf.xml

              - key: console.conf.xml
                path: console.conf.xml

              - key: acl.conf.xml
                path: acl.conf.xml

              - key: switch.conf.xml
                path: switch.conf.xml

              - key: console.conf.xml
                path: console.conf.xml

              - key: logfile.conf.xml
                path: logfile.conf.xml

              - key: sofia.conf.xml
                path: sofia.conf.xml

              - key: voicemail.conf.xml
                path: voicemail.conf.xml

        #
        # Auto Load Secrets
        #
        - name: freeswitch-sms-config
          secret:
            secretName: {{ $fullName }}-freeswitch-sms
            items:
              - key: sms_flowroute.conf.xml
                path: sms_flowroute.conf.xml

        #
        # IVRs
        #

        - name: freeswitch-ivr-config
          configMap:
            name: {{ $fullName }}-freeswitch-ivr-configs
            items:
              - key: demo-ivr.xml
                path: demo-ivr.xml

        #
        # SIP Configs
        #
        - name: freeswitch-sip-config
          configMap:
            name: {{ $fullName }}-freeswitch-sip-configs
            items:
              - key: external.xml
                path: external.xml

              - key: asterisk.xml
                path: asterisk.xml

        #
        # Dial Plans
        #

        - name: freeswitch-dialplan-config
          configMap:
            name: {{ $fullName }}-freeswitch-dialplan-configs
            items:
              - key: default.xml
                path: default.xml

              - key: public.xml
                path: public.xml

        

        #
        # Gateways
        #

        - name: freeswitch-upstream-config
          secret:
            secretName: {{ $fullName }}-freeswitch-upstream
            items:
              - key: flowroute.xml
                path: flowroute.xml

        

        - name: freeswitch-tls-certs
          secret:
            secretName: resolvemyhost-default-certificates
            items:
              - key: tls-combined.pem
                path: agent.pem

              - key: tls.crt
                path: tls.crt


        - name: data-volume
          emptyDir: {}
