{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-freeswitch-sip-configs

data:
  asterisk.xml: |
    <profile name="asterisk">
        <gateways>
          <gateway name="asterisk">
            <param name="username" value="freeswitch"/>
            <param name="realm" value="66.165.222.126"/>
            <param name="password" value="unused-but-required-field"/>
            <param name="from-domain" value="66.165.222.126"/>
            <param name="proxy" value="{{ $fullName }}-asterisk.core-prod.svc.k0s.resolvemy.host"/><!-- ASTERISK ADDRESS -->
            <param name="register" value="false"/><!-- INSTEAD WE SET AOR IN PJSIP.CONF -->
            <param name="cid-type" value="pid"/>
            <param name="rfc-5626" value="true"/>
          </gateway>
        </gateways>
        <settings>
            <param name="apply-inbound-acl" value="asterisk"/>
            <param name="auth-calls" value="false"/>
            <param name="context" value="public"/><!-- WHERE DO CALLS FROM ASTERISK COME INTO? -->
            <param name="rtp-ip" value="10.8.0.3"/><!-- this FreeSWITCH MEDIA IP -->
            <param name="sip-ip" value="10.8.0.3"/><!-- this FreeSWITCH SIP IP -->
        </settings>
    </profile>