{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: {{ $fullName }}-freeswitch-aaa
spec:
  providerConfigRef:
    name: authentik

  writeConnectionSecretToRef:
    namespace: {{ .Release.Namespace }}
    name: {{ $fullName }}-aaa

  forProvider:
    source: Inline
    module: |
      data "authentik_group" "LDAPService" {
        name = "LDAPService"
      }

      resource "random_string" "username" {
        length  = 6
        special = true
      }
  
      resource "random_password" "password" {
        length  = 16
        lower   = true
        numeric = true
        upper   = true
        special = true
      }

      resource "authentik_user" "name" {
        name     = "FreeSwitch"

        username = random_password.username.result
        password = random_password.password.result

        groups   = [data.authentik_group.LDAPService.id]
      }

      output "username" {
        value     = random_password.username.result
        sensitive = true
      }

      output "password" {
        value     = random_password.password.result
        sensitive = true
      }