{{- if .Values.owui.enabled }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ .Release.Name }}-openwebui

spec:
  name: OpenWebUI {{ .Values.region }}-{{ .Values.datacenter }}-{{ .Values.cluster.name }}

  groups:
    - LDAPService

  {{- if .Values.owui.psql.enabled }}
  psql:
    enabled: true

    crossplane:
      crossplaneProvider: {{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.owui.psql.crossplaneProvider }}
      terraformProvider: {{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.owui.psql.terraformProvider }}
  {{- end }}

  writeConnectionSecretToRef:
    name: {{ .Release.Name }}-openwebui-user
{{- end }}
