apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-config

data:
  dovecot.conf: |
    protocols = imap pop3 lmtp
    submission_host = mail.mylogin.space:25
    log_path = /dev/stderr
    info_log_path = /dev/stdout
    debug_log_path = /dev/stdout
    ## this is sometimes needed
    #first_valid_uid = uid-of-vmail-user

    ###############
    # Authentication
    ###############
    auth_mechanisms = plain login

    passdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    userdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    ssl=yes
    ssl_cert=</etc/tls/mail/tls.crt
    ssl_key=</etc/tls/mail/tls.key

    ###############
    # IMAP & POP
    ###############
    protocol imap {
      mail_plugins = $mail_plugins imap_quota
      mail_max_userip_connections = 20
      imap_idle_notify_interval = 29mins
    }

    protocol pop3 {

    }

    service imap-login {
      inet_listener imap {
        port = 143
      }
    }


    ###############
    # Delivery
    ###############
    protocol lmtp {
      mail_plugins = $mail_plugins
    }

    service lmtp {
      inet_listener lmtp {
        port = 2525
      }
    }



    namespace {
      inbox = yes
      separator = /
    }

    !include_try /etc/dovecot/dovecot-storage.conf.ext
