apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-mail-dovecot-auth-config
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-mail-dovecot-auth-config
    template:
      engineVersion: v2
      data:
        test: 'hi'
      templateFrom:
        - configMap:
            # name of the configmap to pull in
            name: business-mail-dovecot-auth-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: dovecot-oauth2.conf.ext
              - key: dovecot-ldap.conf.ext
  data:
    #
    # Database
    #
    - secretKey: OpenIDClientID
      remoteRef:
        key: Dovecot
        property: OpenIDClientID

    - secretKey: OpenIDClientSecret
      remoteRef:
        key: Dovecot
        property: OpenIDClientSecret

    #
    # General AAA
    #
    - secretKey: Username
      remoteRef:
        key: Dovecot
        property: Username

    - secretKey: Password
      remoteRef:
        key: Dovecot
        property: Password
