apiVersion: v1
kind: Service
metadata:
  name: dovecot

  annotations:
    metallb.universe.tf/allow-shared-ip: mail
    metallb.universe.tf/loadBalancerIPs: 66.165.222.125
    io.cilium/lb-ipam-sharing-key: mail
    io.cilium/lb-ipam-ips: 66.165.222.125

spec:
  allocateLoadBalancerNodePorts: false
  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: dovecot
  ports:



    # - name: imap-transport

    #   protocol: TCP
    #   #appProtocol: submissions

    #   port: 2525
    #   targetPort: lmtp


    - name: imaps-default

      protocol: TCP

      port: 993
      targetPort: imaps



    - name: sasl

      protocol: TCP

      port: 12345
      targetPort: sasl

    - name: imap-transport

      protocol: TCP
      #appProtocol: submissions

      port: 2525
      targetPort: lmtp


  loadBalancerIP: 66.165.222.125

  type: LoadBalancer
