apiVersion: v1
kind: Service
metadata:
  name: dovecot

  annotations:
    metallb.universe.tf/allow-shared-ip: mail
spec:
  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: dovecot
  ports:



    # - name: imap-transport

    #   protocol: TCP
    #   #appProtocol: submissions

    #   port: 2525
    #   targetPort: lmtp


    - name: imaps-default

      protocol: TCP

      port: 1993
      targetPort: imaps



    - name: sasl

      protocol: TCP

      port: 12345
      targetPort: sasl


  loadBalancerIP: 10.1.1.25
  externalIPs:
    - 66.165.222.125
  type: LoadBalancer
