apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-mail-dovecot-auth-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core


  target:
    name: business-mail-dovecot-auth-config
    template:
      engineVersion: v2

      templateFrom:
        - configMap:
            # name of the configmap to pull in
            name: business-mail-dovecot-auth-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: dovecot-oauth2.conf.ext
              - key: dovecot-ldap.conf.ext
  data:
    #
    # Database
    #
    - secretKey: OpenIDClientID
      remoteRef:
        key: Mail/Dovecot/OIDC
        property: ClientID

    - secretKey: OpenIDClientSecret
      remoteRef:
        key: Mail/Dovecot/OIDC
        property: ClientSecret

    #
    # General AAA
    #
    - secretKey: Username
      remoteRef:
        key: Mail/Dovecot/LDAP
        property: Username

    - secretKey: Password
      remoteRef:
        key: Mail/Dovecot/LDAP
        property: Password
