apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-config

data:
  dovecot.conf: |
    protocols = imap pop3 lmtp
    submission_host = mail.mylogin.space:25
    log_path = /dev/stderr
    info_log_path = /dev/stdout
    debug_log_path = /dev/stdout
    disable_plaintext_auth = no
    ## this is sometimes needed
    #first_valid_uid = uid-of-vmail-user

    #
    # Users
    #
    lmtp_save_to_detail_mailbox = yes
    recipient_delimiter = +


    ###############
    # Authentication
    ###############
    auth_mechanisms = plain login oauthbearer xoauth2

    passdb {
      driver = ldap

      args = /etc/dovecot/dovecot-ldap.conf.ext
    }

    passdb {
      driver = oauth2
      mechanisms = xoauth2 oauthbearer


      args = /etc/dovecot/dovecot-oauth2.conf.ext
    }

    userdb {
      driver = ldap

      args = /etc/dovecot/dovecot-ldap.conf.ext
    }

    ssl=yes
    ssl_cert=</etc/tls/mail/tls.crt
    ssl_key=</etc/tls/mail/tls.key

    service auth {
      inet_listener {
        port = 12345
      }
    }

    service lmtp {
      inet_listener lmtp {
        port = 2525
      }
    }


    #
    # IMAP
    # 
    mail_location = imapc:
    # Change the line below to reflect the IP address of your Exchange Server.
    imapc_host = int-imap.mylogin.space
    imapc_ssl = imaps

    imapc_port = 993
    imapc_user = %{userdb:uuid}@mylogin.space
    imapc_password = masteruser-secret
    imapc_sasl_mechanisms = login

    service imap {
      # Most of the memory goes to mmap()ing files. You may need to increase this
      # limit if you have huge mailboxes.
      #vsz_limit = $default_vsz_limit

      # Max. number of IMAP processes (connections)
      #process_limit = 1024
    }

    !include /etc/dovecot/namespaces/*.conf
