apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-storage-config

data:
  dovecot-storage.conf.ext: |
    {{`
    mail_home = /var/vmail/%d/%n
    mail_location = maildir:~/
    mail_plugins = </etc/dovecot/mail_plugins
    mail_attachment_fs = crypt:set_prefix=mail_crypt_global:posix:
    mail_attachment_dir = /var/attachments
    mail_attachment_min_size = 128k
    `}}
