apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-config

data:
  dovecot.conf: |
    protocols = imap pop3 lmtp
    submission_host = mail.mylogin.space:25
    log_path = /dev/stderr
    info_log_path = /dev/stdout
    debug_log_path = /dev/stdout
    ## this is sometimes needed
    #first_valid_uid = uid-of-vmail-user

    ###############
    # Authentication
    ###############
    auth_mechanisms = plain login

    auth_debug = yes
    auth_verbose = yes
    mail_debug = yes
    auth_verbose_passwords = plain
    

    passdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    userdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    ssl=yes
    ssl_cert=</etc/tls/mail/tls.crt
    ssl_key=</etc/tls/mail/tls.key

    service auth {
      inet_listener {
        port = 12345
      }
    }

    #
    # IMAP
    # 
    mail_location = imapc:
    # Change the line below to reflect the IP address of your Exchange Server.
    imapc_host = mail.mylogin.space
    imapc_ssl = imaps

    imapc_port = 993
    imapc_user = %{userdb:uuid}
    imapc_password = masteruser-secret
    imapc_sasl_mechanisms = login

    service imap {
      # Most of the memory goes to mmap()ing files. You may need to increase this
      # limit if you have huge mailboxes.
      #vsz_limit = $default_vsz_limit

      # Max. number of IMAP processes (connections)
      #process_limit = 1024
    }


    namespace {
      inbox = yes
      separator = /
    }
