apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-config

data:
  dovecot.conf: |
    protocols = imap pop3 lmtp
    submission_host = mail.mylogin.space:25
    log_path = /dev/stderr
    info_log_path = /dev/stdout
    debug_log_path = /dev/stdout
    ## this is sometimes needed
    #first_valid_uid = uid-of-vmail-user

    ###############
    # Authentication
    ###############
    auth_mechanisms = plain login
    smtpd_sasl_path = inet:mail.mylogin.space:12345
    smtpd_sasl_type = dovecot

    passdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    userdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    ssl=yes
    ssl_cert=</etc/tls/mail/tls.crt
    ssl_key=</etc/tls/mail/tls.key

    service auth {
      inet_listener {
        port = 12345
      }
    }


    namespace {
      inbox = yes
      separator = /
    }
