apiVersion: v1
kind: Service
metadata:
  name: dovecot

  annotations:
    purelb.io/allow-shared-ip: mail.mylogin.space
    purelb.io/service-group: anycast
    purelb.io/allow-local: 'true'
	  purelb.io/addresses: '66.165.222.125'

spec:
  type: LoadBalancer

  allocateLoadBalancerNodePorts: false

  ports:
    - name: imap

      protocol: TCP

      port: 143
      targetPort: imap


    - name: imaps-default

      protocol: TCP

      port: 993
      targetPort: imaps



    - name: sasl

      protocol: TCP

      port: 12345
      targetPort: sasl

    - name: imap-transport

      protocol: TCP
      #appProtocol: submissions

      port: 2525
      targetPort: lmtp

  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: dovecot