apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-config

data:
  dovecot.conf: |
    mail_home=/srv/mail/%Lu

    ## this is sometimes needed
    #first_valid_uid = uid-of-vmail-user

    auth_mechanisms = $auth_mechanisms oauthbearer xoauth2

    passdb {
      driver = oauth2
      mechanisms = xoauth2 oauthbearer
      args = /etc/dovecot/dovecot-oauth2.conf.ext
    }

    passdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    userdb {
      args = /etc/dovecot/dovecot-ldap.conf.ext
      driver = ldap
    }

    ssl=yes
    ssl_cert=/etc/tls/mail/tls.crt
    ssl_key=/etc/tls/mail/tls.key
    # if you are using v2.3.0-v2.3.2.1 (or want to support non-ECC DH algorithms)
    # since v2.3.3 this setting has been made optional.
    #ssl_dh=</path/to/dh.pem

    namespace {
      inbox = yes
      separator = /
    }

    !include_try /etc/dovecot/dovecot-storage.conf.ext
