apiVersion: v1
kind: Service
metadata:
  name: dovecot

  annotations:
    metallb.universe.tf/allow-shared-ip: mail
spec:
  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: dovecot
  ports:
    - name: imap-auth

      protocol: TCP
      #appProtocol: smtp

      port: 2102
      targetPort: auth


    - name: imap-transport

      protocol: TCP
      #appProtocol: submissions

      port: 2525
      targetPort: lmtp


    - name: imap-default

      protocol: TCP
      #appProtocol: submission

      port: 143
      targetPort: imap


    - name: pop3

      protocol: TCP

      port: 110
      targetPort: pop3


    - name: sieve

      protocol: TCP

      port: 4190
      targetPort: sieve


  loadBalancerIP: 10.1.1.25
  externalIPs:
    - 66.165.222.125
  type: LoadBalancer
