apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: office-user

spec:
  name: Maddy Email

  database:
    name: email

  buckets:
    - mail-main

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ .Release.Name }}-maddy-creds