apiVersion: v1
kind: Service
metadata:
  name: maddy

  annotations:
    metallb.universe.tf/allow-shared-ip: mail
spec:
  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: maddy
  ports:
    - name: imap-default

      protocol: TCP
      appProtocol: imap

      port: 143
      targetPort: imap


    - name: imaps-default

      protocol: TCP
      appProtocol: imaps

      port: 993
      targetPort: imaps


    - name: imap-transport

      protocol: TCP
      #appProtocol: submissions

      port: 2525
      targetPort: lmtp


  loadBalancerIP: 10.1.1.25
  externalIPs:
    - 66.165.222.125
  type: LoadBalancer
