apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-maddy-config-tpl

data:
  checkScript.sh: |
    #!/bin/sh

    echo "stuff ${@}"

    exit 0
  maddy.conf: |
    $(hostname) = mail.mylogin.space
    $(primary_domain) = mylogin.space
    $(local_domains) = $(primary_domain)

    tls file /etc/tls/mail/tls.crt /etc/tls/mail/tls.key

    {{`

    storage.imapsql local_mailboxes {
      driver postgres
      dsn "user={{ .Username }} password={{ .Password }} host=psql.service.dc1.kjdev dbname=email sslmode=disable"

      

      msg_store s3 {
        endpoint s3.mylogin.space
        secure yes

        access_key "{{ .S3AccessKey }}"
        secret_key "{{ .S3SecretKey }}"
        bucket mail-main

        # optional
        region us-east-1
        object_prefix maddy/
      }
    }

    # LMTP
    lmtp tcp://0.0.0.0:2525 {
      hostname mail.mylogin.space

      max_message_size 150M
      max_header_size 10M

      deliver_to &local_mailboxes
    }

    # ----------------------------------------------------------------------------
    # IMAP endpoints

    imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
        auth plain_separate {
          user ldap {
            debug on

            urls ldaps://ldap.mylogin.space:636
            bind plain "cn={{ .Username }},ou=users,dc=ldap,dc=mylogin,dc=space" "{{ .Password }}"

            base_dn "ou=users,dc=ldap,dc=mylogin,dc=space"
            filter "(uid={username})"
          }
        
          pass pass_table static {
              entry 38e31197e97aaa5b6c6e4cc33c9b8a5c9734877557dae657763b5ec32c890fd8 bcrypt:$2a$10$uSUL5piqbh5ZYikm5LCUeuGsgr5IC2xLQktXssCGjAIoxeM7tyFfq
          }
        }
        storage &local_mailboxes

        insecure_auth true
        io_debug yes
        debug yes
    }`}}
