apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-maddy-config-tpl

data:
  maddy.conf: |
    $(hostname) = mail.mylogin.space
    $(primary_domain) = mylogin.space
    $(local_domains) = $(primary_domain)

    tls file /etc/tls/mail/tls.crt /etc/tls/mail/tls.key

    {{`

    storage.imapsql local_mailboxes {
      driver postgres
      dsn "user={{ .Username }} password={{ .Password }} host=psql.service.dc1.kjdev dbname=email sslmode=disable"

      debug true

      

      msg_store s3 {
        endpoint s3.mylogin.space
        secure yes

        access_key "{{ .S3AccessKey }}"
        secret_key "{{ .S3SecretKey }}"
        bucket mail-main

        # optional
        region us-east-1
        object_prefix maddy/
      }
    }`}}

    # LMTP
    lmtp tcp://0.0.0.0:2525 {
      hostname mail.mylogin.space

      deliver_to &local_mailboxes
    }

    # ----------------------------------------------------------------------------
    # IMAP endpoints

    imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
        auth ldap local_authdb {
            debug true

            dn_template "cn={username},ou=users,dc=ldap,dc=mylogin,dc=space"

            urls ldaps://ldap.mylogin.space:636
            bind plain "cn={{ .Username }},ou=users,dc=ldap,dc=mylogin,dc=space" "{{ .Password }}"
          }
        }
        storage &local_mailboxes
        debug true
        io_debug true
        io_errors true
        insecure_auth true
    }
