apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-maddy
  labels:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: maddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mail
      app.kubernetes.io/component: maddy

  template:
    metadata:
      labels:
        app.kubernetes.io/name: mail
        app.kubernetes.io/component: maddy
        logs: loki-myloginspace

    spec:
      volumes:
        - name: maddy-config
          configMap:
            name: business-mail-maddy-config
            items:
              - key: maddy.conf
                path: maddy.conf

              - key: checkScript.sh
                path: checkScript.sh

        #
        # Secrets and Certificates
        #

        - name: tls-certs
          secret:
            secretName: {{ .Values.email.tls.secretName }}

      containers:
        - name: maddy
          #
          # TODO: Get Renovate managing this and setup proper tests
          #
          image: foxcpp/maddy:0.6.2
          stdin: true
          tty: true

          env:
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maddy-s3
                  key: AccessKey

            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maddy-s3
                  key: SecretKey

            - name: PSQL_HOSTNAME
              value: 'psql.mylogin.space'

            - name: PSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maddy-creds
                  key: psqlPort

            - name: PSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maddy-creds
                  key: database

            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maddy-creds
                  key: username

            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-maddy-creds
                  key: password

          volumeMounts:
            #
            # Configs
            #
            - name: maddy-config
              mountPath: /data/maddy.conf
              subPath: maddy.conf

            - name: maddy-config
              mountPath: /data/checkScript.sh
              subPath: checkScript.sh


            #
            # Secrets and Certificates
            #
            - name: tls-certs
              mountPath: /etc/tls/mail

          ports:
            - name: lmtp
              containerPort: 2525
              protocol: TCP

            - name: imaps
              containerPort: 993
              protocol: TCP

            - name: imap
              containerPort: 143
              protocol: TCP

