apiVersion: v1
kind: Service
metadata:
  name: maddy

  labels:
    lan-mode: private

  annotations:
    metallb.universe.tf/allow-shared-ip: mail
    external-dns.alpha.kubernetes.io/hostname: 'int-imap.mylogin.space'

spec:
  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: maddy
  ports:
    - name: imap-default

      protocol: TCP
      appProtocol: imap

      port: 143
      targetPort: imap


    - name: imaps-default

      protocol: TCP
      appProtocol: imaps

      port: 993
      targetPort: imaps

  publishNotReadyAddresses: true
  loadBalancerIP: 10.1.1.25

  type: LoadBalancer
