apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-maddy-config-tpl

data:
  maddy.conf: |
    $(hostname) = mail.mylogin.space
    $(primary_domain) = mylogin.space
    $(local_domains) = $(primary_domain)

    tls file /etc/tls/mail/tls.crt /etc/tls/mail/tls.key

    {{`
    auth.ldap {
        base_dn "ou=users,dc=ldap,dc=mylogin,dc=space"
        filter "(&(objectClass=posixAccount)(email={username}))"
        urls ldaps://ldap.mylogin.space:636
        bind plain "cn={{ .Username }},ou=users,dc=ldap,dc=mylogin,dc=space" "{{ .Password }}"

        # DN lookup params.
        search_base_dn "ou=users,dc=ldap,dc=mylogin,dc=space"
    }
    `}}

    # imapsql module stores all indexes and metadata necessary for IMAP using a
    # relational database. It is used by IMAP endpoint for mailbox access and
    # also by SMTP & Submission endpoints for delivery of local messages.
    #
    # IMAP accounts, mailboxes and all message metadata can be inspected using
    # imap-* subcommands of maddyctl utility.
    {{`
    storage.imapsql local_mailboxes {
      driver postgres
      dsn "user={{ .Username }} password={{ .Password }} host=psql.service.dc1.kjdev dbname=email sslmode=disable"



      msg_store s3 {
        endpoint s3.mylogin.space
        secure yes

        access_key "{{ .S3AccessKey }}"
        secret_key "{{ .S3SecretKey }}"
        bucket mail-main

        # optional
        region us-east-1
        object_prefix maddy/
      }
    }
    `}}

    # LMTP
    lmtp tcp://0.0.0.0:2525 {
      hostname mail.mylogin.space

      deliver_to &local_mailboxes
    }

    # ----------------------------------------------------------------------------
    # IMAP endpoints

    imap tls://0.0.0.0:993 tcp://0.0.0.0:143 {
        auth ldap
        storage &local_mailboxes
    }
