apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: simplelogin-postfix-config
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: simplelogin-postfix-config
    template:
      engineVersion: v2
      data:
        test: 'hi'
      templateFrom:
        - configMap:
            name: simplelogin-postfix-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: pgsql-relay-domains.cf
              - key: pgsql-transport-maps.cf
  data:
    #
    # Database
    #
    - secretKey: DatabaseDatabase
      remoteRef:
        key: SimpleLogin
        property: DatabaseDatabase

    - secretKey: DatabasePassword
      remoteRef:
        key: SimpleLogin
        property: DatabasePassword

    - secretKey: DatabaseUser
      remoteRef:
        key: SimpleLogin
        property: DatabaseUser
