apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplelogin-postfix
  labels:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simplelogin
      app.kubernetes.io/component: postfix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simplelogin
        app.kubernetes.io/component: postfix
    spec:
      volumes:
        - name: simplelogin-configs
          secret:
            secretName: simplelogin-postfix-config
            optional: false
            items:
              - key: pgsql-relay-domains.cf
                path: pgsql-relay-domains.cf

              - key: pgsql-transport-maps.cf
                path: pgsql-transport-maps.cf

        - name: ldap-configs
          secret:
            secretName: business-mail-postfix-auth-config
            optional: false
            items:
              - key: ldap-in.cf
                path: ldap-in.cf

              - key: ldap-auth.cf
                path: ldap-auth.cf

        - name: tls-certs
          secret:
            secretName: {{ .Values.email.tls.secretName }}

        - name: dkim-secrets
          secret:
            secretName: selector1-mail-myloginspace
            items:
            - key: mail.mylogin.space.selector1.key
              path: dkim.key

      containers:
        - name: postfix
          image: registry.writemy.codes/teleport/postfix-pg
          envFrom:
            - secretRef:
                name: business-mail-simplelogin-postfix-db-prod

            - configMapRef:
                name: simplelogin-postfix-cfg

          volumeMounts:
            - name: simplelogin-configs
              mountPath: /etc/postfix/pgsql-relay-domains.cf
              subPath: pgsql-relay-domains.cf

            - name: simplelogin-configs
              mountPath: /etc/postfix/pgsql-transport-maps.cf
              subPath: pgsql-transport-maps.cf

            #
            # Dovecot
            #

            #
            # AAA LDAP
            #
            - name: ldap-configs
              mountPath: /etc/postfix/ldap.cf
              subPath: ldap-in.cf

            - name: ldap-configs
              mountPath: /etc/postfix/ldap.cf
              subPath: ldap-auth.cf

            - name: tls-certs
              mountPath: /etc/tls/mail

            - mountPath: /secret/dkim.key
              name: dkim-secrets
              subPath: dkim.key

          ports:
            - name: smtp
              containerPort: 25

            - name: smtp-tls 
              containerPort: 465

            - name: smtp-starttls
              containerPort: 587

            - name: smtp-auth
              containerPort: 10025

