apiVersion: v1
kind: ConfigMap
metadata:
  name: simplelogin-postfix-aaa-config-tpl
data:
  ldap.cf: |
    {{`
    server_host = ldap://ldap.mylogin.space
    start_tls = yes
    version = 3

    bind = yes
    bind_dn = cn={{ .Username }},ou=users,dc=ldap,dc=mylogin,dc=space
    bind_pw = {{ .Password }}

    search_base = ou=users,dc=ldap,dc=mylogin,dc=space
    scope = sub
    `}}
