apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplelogin-postfix
  labels:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: postfix
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: simplelogin
      app.kubernetes.io/component: postfix
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simplelogin
        app.kubernetes.io/component: postfix
    spec:
      containers:
        - name: postfix
          image: dhet/postfix-pg:latest
          ports:
            - containerPort: 25
              name: smtp

            - containerPort: 587
              name: smtps
