apiVersion: v1
kind: ConfigMap
metadata:
  name: simplelogin-postfix-cfg
data:
  CONF_APPEND_DOT_MYDOMAIN: 'no'

  CONF_MYNETWORKS: '10.0.0.0/8'


  #
  # TLS
  #
  CONF_SMTPD_TLS_CERT_FILE: '/etc/tls/mail/tls.crt'
  CONF_SMTPD_TLS_KEY_FILE: '/etc/tls/mail/tls.key'
  CONF_SMTPD_TLS_SESSION_CACHE_DATABASE: 'btree:${data_directory}/smtpd_scache'
  CONF_SMTP_TLS_SESSION_CACHE_DATABASE: 'btree:${data_directory}/smtp_scache'
  CONF_SMTP_TLS_SECURITY_LEVEL: 'may'
  CONF_SMTPD_TLS_SECURITY_LEVEL: 'may'
  CONF_SMTPD_SASL_PATH: 'inet:mail.mylogin.space:12345'  
  CONF_SMTPD_SASL_TYPE: 'dovecot'
  CONF_SMTPD_SASL_AUTH_ENABLE: 'yes'
  CONF_BROKEN_SASL_AUTH_CLIENTS: 'yes'

  #
  # My Hosts
  #
  CONF_MYDESTINATION: ''
  CONF_MYHOSTNAME: 'mail.mylogin.space'
  CONF_MYDOMAIN: 'mail.mylogin.space'
  CONF_MYORIGIN: 'mail.mylogin.space'

  CONF_VIRTUAL_TRANSPORT: 'lmtp:inet:mail.mylogin.space:2525'
  CONF_VIRTUAL_MAILBOX_DOMAINS: 'mylogin.space'
  #CONF_VIRTUAL_ALIAS_MAPS: 'ldap:/etc/postfix/ldap.cf'
  CONF_VIRTUAL_MAILBOX_MAPS: 'ldap:/etc/postfix/ldap-in.cf'
  CONF_LMTP_HOST_LOOKUP: 'native'
  CONF_SMTPD_SENDER_LOGIN_MAPS: 'ldap:/etc/postfix/ldap-auth.cf'


  #
  # HELO Restrictions
  #
  CONF_SMTPD_DELAY_REJECT: 'yes'
  CONF_SMTPD_HELO_REQUIRED: 'yes'
  CONF_SMTPD_HELO_RESTRICTIONS: |
    permit_mynetworks,reject_non_fqdn_helo_hostname,reject_invalid_helo_hostname,permit

  #
  # Sender Restrictions
  #
  CONF_SMTPD_SENDER_RESTRICTIONS: |
    permit_mynetworks,reject_non_fqdn_sender,reject_unknown_sender_domain,permit

  #
  # Recipient Restrictions
  #
  CONF_SMTPD_RECIPIENT_RESTRICTIONS: |
    reject_unauth_pipelining,reject_non_fqdn_recipient,reject_unknown_recipient_domain,permit_mynetworks,permit

  CONF_SMTPD_RELAY_RESTRICTIONS: |
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_unauth_destination
