apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: simplelogin-postfix-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core
  
  target:
    name: simplelogin-postfix-config
    template:
      engineVersion: v2

      templateFrom:
        - configMap:
            name: simplelogin-postfix-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: pgsql-relay-domains.cf
              - key: pgsql-transport-maps.cf
  data:
    #
    # Database
    #
    - secretKey: DatabaseDatabase
      remoteRef:
        key: Mail/SimpleLogin/Database
        property: Database

    - secretKey: DatabasePassword
      remoteRef:
        key: Mail/SimpleLogin/Database
        property: Password

    - secretKey: DatabaseUser
      remoteRef:
        key: Mail/SimpleLogin/Database
        property: Username
