apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-mail-postfix-auth-config
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-mail-postfix-auth-config
    template:
      engineVersion: v2
      data:
        test: 'hi'
      templateFrom:
        - configMap:
            # name of the configmap to pull in
            name: simplelogin-postfix-aaa-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: ldap=in.cf
              - key: ldap-auth.cf
  data:
    #
    # General AAA
    #
    - secretKey: Username
      remoteRef:
        key: Postfix
        property: Username

    - secretKey: Password
      remoteRef:
        key: Postfix
        property: Password
