apiVersion: v1
kind: Service
metadata:
  name: postfix
  annotations:
    metallb.universe.tf/allow-shared-ip: mail
spec:
  selector:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: postfix
  ports:
    - name: smtp

      protocol: TCP
      appProtocol: smtp

      port: 25
      targetPort: smtp


    - name: submissions

      protocol: TCP
      appProtocol: submissions

      port: 465
      targetPort: smtp-tls


    - name: smtp-starttls

      protocol: TCP
      appProtocol: submission

      port: 587
      targetPort: smtp-starttls


    - name: smtp-auth

      protocol: TCP

      port: 10025
      targetPort: smtp-auth

  # publishNotReadyAddresses: true
  loadBalancerIP: 10.1.1.25
  externalIPs:
    - 66.165.222.125
  type: LoadBalancer
