apiVersion: v1
kind: Service
metadata:
  name: rspamd

  labels:
    lan-mode: private
    wan-mode: public

  annotations:
    external-dns.alpha.kubernetes.io/hostname: 'int-rspamd.mylogin.space'

spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: rspam
    app.kubernetes.io/worker: proxy

  ports:
    - name: proxy

      protocol: TCP

      port: 11332
      targetPort: proxy


    - name: normal

      protocol: TCP

      port: 11333
      targetPort: normal


    - name: controller

      protocol: TCP

      port: 11334
      targetPort: controller

  type: ClusterIP