apiVersion: v1
kind: Service
metadata:
  name: rspamd-proxy

  labels:
    lan-mode: private
    wan-mode: public
spec:
  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: rspam
    app.kubernetes.io/worker: proxy

  ports:
    - name: proxy

      protocol: TCP

      port: 11332
      targetPort: proxy

  type: ClusterIP