apiVersion: v1
kind: Service
metadata:
  name: rspamd-normal

  labels:
    lan-mode: private
    wan-mode: public

spec:
  selector:
    app.kubernetes.io/name: mail
    app.kubernetes.io/component: rspam
    app.kubernetes.io/worker: normal

  ports:
    - name: main

      protocol: TCP
      appProtocol: imap

      port: 11333
      targetPort: 11333

  type: ClusterIP