apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplelogin-api
  labels:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simplelogin
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simplelogin
        app.kubernetes.io/component: api
    spec:
      volumes:
        - name: simplelogin-data
          emptyDir:
            medium: Memory

        - name: config-env
          secret:
            secretName: business-mail-simplelogin-db-prod

        - name: words
          configMap:
            name: simplelogin-config-wordlist
            items:
              - key: test_words.txt
                path: test_words.txt

      initContainers:

        - name: simplelogin-initapp
          image: registry.writemy.codes/teleport/simplelogin

          envFrom:
            - secretRef:
                name: business-mail-simplelogin-db-prod
          
            - configMapRef:
                name: simplelogin-config


          command: ['python']
          args:
            - init_app.py

          volumeMounts:
            - mountPath: /sl
              name: simplelogin-data

            - mountPath: /code/.env
              name: config-env
              subPath: SLENV

            - mountPath: /code/local_data/words.txt
              name: words
              subPath: test_words.txt

      containers:
        - name: simplelogin-api
          image: registry.writemy.codes/teleport/simplelogin

          envFrom:
            - secretRef:
                name: business-mail-simplelogin-db-prod

            - configMapRef:
                name: simplelogin-config

          ports:
            - containerPort: 7777
              name: http

          volumeMounts:
            - mountPath: /sl
              name: simplelogin-data

            - mountPath: /code/.env
              name: config-env
              subPath: SLENV

            - mountPath: /code/local_data/words.txt
              name: words
              subPath: test_words.txt
