apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplelogin-api
  labels:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simplelogin
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simplelogin
        app.kubernetes.io/component: api
    spec:
      volumes:
        - name: simplelogin-data
          persistentVolumeClaim:
            claimName: simplelogin-data

        - name: config-env
          secret:
            secretName: business-mail-simplelogin-db-prod

        - name: dkim-public
          configMap:
            name: simplelogin-dkim-public-cert
            items:
              - key: dkim.pub.key
                path: dkim.pub.key

        - name: dkim-secrets
          secret:
            secretName: selector1-mail-myloginspace
            items:
            - key: mail.mylogin.space.selector1.key
              path: dkim.key

      initContainers:
        - name: simplelogin-initdb
          image: simplelogin/app-ci:v4.5.2
          tty: true 
          
          envFrom:
            - secretRef:
                name: business-mail-simplelogin-db-prod

            - configMapRef:
                name: simplelogin-config

          command: ['flask']          
          args:
            - db
            - upgrade
      
          volumeMounts:
            - mountPath: /sl
              name: simplelogin-data

            - mountPath: /code/.env
              name: config-env
              subPath: SLENV

            - mountPath: /secret/dkim.key
              name: dkim-secrets
              subPath: dkim.key

            - mountPath: /secret/dkim.pub.key
              name: dkim-public
              subPath: dkim.pub.key

        - name: simplelogin-initapp
          image: simplelogin/app-ci:v4.5.2

          envFrom:
            - secretRef:
                name: business-mail-simplelogin-db-prod
          
            - configMapRef:
                name: simplelogin-config


          command: ['python']
          args:
            - init_app.py

          volumeMounts:
            - mountPath: /sl
              name: simplelogin-data

            - mountPath: /code/.env
              name: config-env
              subPath: SLENV

            - mountPath: /secret/dkim.key
              name: dkim-secrets
              subPath: dkim.key

            - mountPath: /secret/dkim.pub.key
              name: dkim-public
              subPath: dkim.pub.key

      containers:
        - name: simplelogin-api
          image: simplelogin/app-ci:v4.5.2

          envFrom:
            - secretRef:
                name: business-mail-simplelogin-db-prod

            - configMapRef:
                name: simplelogin-config

          ports:
            - containerPort: 7777
              name: http

          volumeMounts:
            - mountPath: /sl
              name: simplelogin-data

            - mountPath: /code/.env
              name: config-env
              subPath: SLENV

            - mountPath: /secret/dkim.key
              name: dkim-secrets
              subPath: dkim.key

            - mountPath: /secret/dkim.pub.key
              name: dkim-public
              subPath: dkim.pub.key

