apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplelogin-mailhandler
  labels:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: mailhandler
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: simplelogin
      app.kubernetes.io/component: mailhandler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simplelogin
        app.kubernetes.io/component: mailhandler
    spec:
      volumes:
        - name: simplelogin-data
          emptyDir:
            medium: Memory

        - name: config-env
          secret:
            secretName: business-mail-simplelogin-db-prod

        - name: words
          configMap:
            name: simplelogin-config-wordlist
            items:
              - key: test_words.txt
                path: test_words.txt

      containers:
        - name: simplelogin
          image: registry.writemy.codes/teleport/simplelogin
          command: ['python']
          args: ['email_handler.py']

          envFrom:
            - secretRef:
                name: business-mail-simplelogin-db-prod

            - configMapRef:
                name: simplelogin-config

          ports:
            - containerPort: 20381
              name: smtp

          volumeMounts:
            - mountPath: /sl
              name: simplelogin-data

            - mountPath: /code/.env
              name: config-env
              subPath: SLENV

            - mountPath: /code/local_data/test_words.txt
              name: words
              subPath: test_words.txt
