apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-mail-simplelogin-db-prod-sync
spec:
  refreshInterval: '5m'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-mail-simplelogin-db-prod
    template:
      engineVersion: v2
      data:
        PGDATABASE: '{{ .DatabaseDatabase }}'
        
        PGHOST: psql.service.dc1.kjdev
        PGPORT: '5432'

        PGSSLMODE: disable
        
        PGUSER: '{{ .DatabaseUser }}'
        PGPASSWORD: '{{ .DatabasePassword }}'
  data:
    - secretKey: DatabaseDatabase
      remoteRef:
        key: SimpleLogin
        property: DatabaseDatabase

    - secretKey: DatabasePassword
      remoteRef:
        key: SimpleLogin
        property: DatabasePassword

    - secretKey: DatabaseUser
      remoteRef:
        key: SimpleLogin
        property: DatabaseUser
