apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 'business-communications-mattermost-db-sync-{{ .Values.environment }}'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: 'business-communications-mattermost-db-{{ .Values.environment }}'
    template:
      engineVersion: v2
      data:
        DatabaseURI: '{{`{{ .Username }}:{{ .Password }}@{{ .Hostname }}:{{ .Port }}/{{ .Database }}&connect_timeout=10`}}'

        DB_CONNECTION_STRING: '{{`postgres://{{ .Username }}:{{ .Password }}@{{ .Hostname }}:{{ .Port }}/{{ .Database }}&connect_timeout=10`}}'
  
  data:
    - secretKey: Hostname
      remoteRef:
        key: Mattermost/Database
        property: Hostname

    - secretKey: Port
      remoteRef:
        key: Mattermost/Database
        property: Port

    - secretKey: Database
      remoteRef:
        key: Mattermost/Database
        property: Database

    - secretKey: Username
      remoteRef:
        key: Mattermost/Database
        property: Username

    - secretKey: Password
      remoteRef:
        key: Mattermost/Database
        property: Password
