apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: 'business-communications-s3-sync-{{ .Values.environment }}'
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: 'business-communications-s3-{{ .Values.environment }}'

  data:
    - secretKey: bucket
      remoteRef:
        key: Mattermost/S3
        property: Bucket

    - secretKey: accesskey
      remoteRef:
        key: Mattermost/S3
        property: AccessKey
      
    - secretKey: secretkey
      remoteRef:
        key: Mattermost/S3
        property: SecretKey
