apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: 'mattermost-sync-{{ .Values.mattermost-team-edition.environment }}'
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: 'mattermost-synced-{{ .Values.mattermost-team-edition.environment }}'
    template:
      data:
        DatabaseURI: '{{`postgres://{{ .DatabaseUsername | toString }}:{{ .DatabasePassword | toString }}@{{ .DatabaseHostname | toString }}:{{ .DatabasePort | toString }}/{{ .DatabaseDatabase | toString }}?sslmode=disable`}}'

  data:
    ################### 
    # Database Config #
    ###################

    - secretKey: DatabaseDatabase
      remoteRef:
        key: Mattermost
        property: DatabaseDatabase


    - secretKey: DatabaseHostname
      remoteRef:
        key: Mattermost
        property: DatabaseHostname

    - secretKey: DatabasePort
      remoteRef:
        key: Mattermost
        property: DatabasePort

    #
    # Database Credentials
    #

    - secretKey: DatabaseUsername
      remoteRef:
        key: Mattermost
        property: DatabaseUsername

    - secretKey: DatabasePassword
      remoteRef:
        key: Mattermost
        property: DatabasePassword


    #
    # GitLab Config
    #

    - secretKey: GitLabClientID
      remoteRef:
        key: Mattermost
        property: GitLabClientID

    - secretKey: GitLabClientSecret
      remoteRef:
        key: Mattermost
        property: GitLabClientSecret
