vikunja:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  controller:
    strategy: RollingUpdate

  image:
    # -- Caddy reverse proxy image and tag
    repository: caddy
    # -- vikunja api image tag
    tag: 2.4.2-alpine
    # vikunja api image pull policy
    pullPolicy: IfNotPresent

  postgresql:
    enabled: false

  caddy:
    # -- Disable auto tls if behind another loadbalancer or ingress
    noTls: false

  vikunja:
    # -- Provide Vikunja config as YAML string
    config: |-
      
      auth:
        openid:
          # Enable or disable OpenID Connect authentication
          enabled: true
          # The url to redirect clients to. Defaults to the configured frontend url. If you're using Vikunja with the official
          # frontend, you don't need to change this value.
          # **Note:** The redirect url must exactly match the configured redirect url with the third party provider.
          # This includes all slashes at the end or protocols.
          redirecturl: https://tasks.mylogin.space/auth/openid/
          # A list of enabled providers
          providers:
            # The name of the provider as it will appear in the frontend.
            - name: authentik
              # The auth url to send users to if they want to authenticate using OpenID Connect.
              authurl: https://idp.mylogin.space/application/o/Vikunja/
              # The client ID used to authenticate Vikunja at the OpenID Connect provider.
              clientid: <secret:CORE0_SITE1/data/Vikunja~OpenIDClientID>
              # The client secret used to authenticate Vikunja at the OpenID Connect provider.
              clientsecret: <secret:CORE0_SITE1/data/Vikunja~OpenIDClientSecret>


  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 8080

  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: false

  additionalContainers:
    # -- Set up the vikunja API container.
    # @default -- See values.yaml
    api:
      name: api
      # -- Vikunja api image and tag
      image: vikunja/api:0.19.1
      imagePullPolicy: IfNotPresent
      # -- You can declare most Vikunja parameters as environment variables.
      # Please consult https://vikunja.io/docs/config-options/ to see all parameters.
      # Note that parameters that are an array cannot be defined as environment variables (like the OpenID Connect settings). Use the vikunja.config Value for that.
      # @default -- See below
      env:
        - name: VIKUNJA_SERVICE_JWTSECRET
          valueFrom:
            secretKeyRef:
              name: vikunja-jwt-prod
              key: SecretKey

        - name: VIKUNJA_DATABASE_TYPE
          value: 'postgres'

        - name: VIKUNJA_DATABASE_HOST
          value: psql.service.dc1.kjdev

        - name: VIKUNJA_DATABASE_DATABASE
          valueFrom:
            secretKeyRef:
              name: vikunja-db-prod-sync
              key: DatabaseDatabase

        - name: VIKUNJA_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: vikunja-db-prod-sync
              key: DatabaseUsername

        - name: VIKUNJA_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vikunja-db-prod-sync
              key: DatabasePassword
      volumeMounts:
        - name: vikunja-config
          mountPath: /etc/vikunja/config.yml
          subPath: Vikunja.yaml
        # - name: files
        #   mountPath: /app/vikunja/files

    # -- Set up the vikunja frontend container.
    # @default -- See values.yaml
    frontend:
      name: frontend
      # -- Vikunja frontend image and tag
      image: vikunja/frontend:0.19.1
      imagePullPolicy: IfNotPresent

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
  # -- Volume used for static files
    files:
      enabled: false
      mountpath: /app/vikunja/files
