vaultwarden:  
  image:
    # -- image repository
    repository: vaultwarden/server
    # -- image pull policy
    pullPolicy: IfNotPresent

    podLabels:
      sidecar.istio.io/inject: 'true'

    podAnnotations:
      sidecar.istio.io/inject: 'true'

  strategy:
    type: Recreate


  # -- Configures service settings for the chart. Normally this does not need to be modified.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 80
        websocket:
          enabled: true
          port: 3012

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: false

  # https://github.com/bitnami/charts/tree/master/bitnami/mariadb/#installing-the-chart
  mariadb:
    enabled: false

  # https://github.com/bitnami/charts/tree/master/bitnami/postgresql/#installing-the-chart
  postgresql:
    enabled: false
