apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-testing-liberespeed-db-prod-sync
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-testing-liberespeed-db-prod
  data:
    - secretKey: Database
      remoteRef:
        key: LibreSpeed
        property: Database

    - secretKey: Username
      remoteRef:
        key: LibreSpeed
        property: Username
      
    - secretKey: Password
      remoteRef:
        key: LibreSpeed
        property: Password
