apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: business-testing-liberespeed-db-prod-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-testing-liberespeed-db-prod

  data:
    - secretKey: Database
      remoteRef:
        key: LibreSpeed/Database
        property: Database

    - secretKey: Username
      remoteRef:
        key: LibreSpeed/Database
        property: Username
      
    - secretKey: Password
      remoteRef:
        key: LibreSpeed/Database
        property: Password
