apiVersion: http://gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: cybercheft-ingress
  labels:
    wan-mode: 'public'
    lan-mode: 'private'
spec:
  parentRefs:
    -	name: ingress-gw
  hostnames:
    - 'cyberchef.mylogin.space'
  rules:
    -	backendRefs:
        -	name: cyberchef-ui
          port: 80