global:
  createDefaultServiceAccount: false

gateway:
  name: 'main-gw'
  namespace: 'core-prod'
  sectionName: 'https-myloginspace'

cyberchef:
  domain: 'cyberchef.mylogin.space'
  replicas: 2

  image:
    repository: 'mpepping/cyberchef'
    tag: 'latest@sha256:45ac7df48354fb86bcd6e90710627353ad59980e410917165ae6c24780b44fab'
    pullPolicy: 'IfNotPresent'

  resources: {}
