controllers:
  cyberchef:
    # For Deployments, valid values are Recreate (default) and RollingUpdate.
    # For StatefulSets, valid values are OnDelete and RollingUpdate (default).
    # DaemonSets/CronJobs ignore this.
    strategy: RollingUpdate

    revisionHistoryLimit: 3

    nameOverride: cyberchef

    containers:
      cyberchef:
        image:
          repository: mpepping/cyberchef

          #
          # TODO: Get this fully automated with Renovate or similar
          #
          tag: v10.19.4
          pullPolicy: IfNotPresent


        # -- Probe configuration
        # -- [[ref]](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)
        # @default -- See below
        probes:
          # -- Liveness probe configuration
          # @default -- See below
          liveness:
            # -- Enable the liveness probe
            enabled: false

          # -- Redainess probe configuration
          # @default -- See below
          readiness:
            # -- Enable the readiness probe
            enabled: false

          # -- Startup probe configuration
          # @default -- See below
          startup:
            # -- Enable the startup probe
            enabled: false

service:
  mqttx:
    # -- Enables or disables the service
    enabled: true

    # -- Configure which controller this service should target
    controller: cyberchef

    nameOverride: cyberchef

    # -- Make this the primary service for this controller (used in probes, notes, etc...).
    # If there is more than 1 service targeting the controller, make sure that only 1 service is
    # marked as primary.
    primary: true

    # -- Set the service type
    type: ClusterIP




    ports:
      http:
        # -- Enables or disables the port
        enabled: true

        primary: true
      
        # -- The port number
        port: 80

        # -- Port protocol.
        # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
        # HTTP and HTTPS spawn a TCP service and get used for internal URL and name generation
        protocol: HTTP