global:
  createDefaultServiceAccount: true

gateway:
  name: 'main-gw'
  namespace: 'core-prod'
  sectionName: 'https-myloginspace'

k8gb:
  enabled: true
  strategy: 'roundRobin'
  dnsTtlSeconds: 30

cyberchef:
  domains:
    - 'cyberchef.mylogin.space'
  replicas: 2

  image:
    repository: ghcr.io/gchq/cyberchef
    tag: 'latest'
    pullPolicy: 'IfNotPresent'

  resources:
    requests:
      cpu: '25m'
      memory: '64Mi'
    limits:
      cpu: '500m'
      memory: '256Mi'
