apiVersion: v2
name: 'core-business-firefly'
description: 'Firefly III and optional finance dashboards using BJW-S Common'
type: 'application'
version: '1.0.0'
appVersion: '6.6.6'
kubeVersion: '>=1.31.0-0'
home: 'https://www.firefly-iii.org/'
sources:
  - 'https://github.com/firefly-iii/firefly-iii'
  - 'https://github.com/firefly-iii/kubernetes'
  - 'https://github.com/eitchtee/WYGIWYH'
  - 'https://github.com/giorobert88/financial-dashboard'
dependencies:
  - name: 'common'
    version: '5.0.1'
    repository: 'https://bjw-s-labs.github.io/helm-charts/'
