{{- if and .Values.sharing.kutt.enabled .Values.sharing.kutt.redis.enabled .Values.sharing.kutt.redis.ownDragonfly.enabled }}
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: '{{ .Values.sharing.kutt.redis.ownDragonfly.passwordGeneratorName }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  length: 64
  digits: 16
  symbols: 0
  allowRepeat: true
  secretKeys:
    - 'password'
  encoding: 'base64url'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ .Values.sharing.kutt.redis.ownDragonfly.passwordSecretName }}-generate'
  annotations:
    argocd.argoproj.io/sync-wave: '-9'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: '{{ .Values.sharing.kutt.redis.ownDragonfly.passwordSecretName }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: 'Password'
          name: '{{ .Values.sharing.kutt.redis.ownDragonfly.passwordGeneratorName }}'
{{- end }}
