{{- if and .Values.sharing.kutt.enabled .Values.sharing.kutt.redis.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'sharing-kutt-dragonfly'
spec:
  refreshInterval: '30s'
  secretStoreRef:
    kind: '{{ .Values.sharing.kutt.redis.secretStoreRef.kind }}'
    name: '{{ .Values.sharing.kutt.redis.secretStoreRef.name }}'
  target:
    name: '{{ .Values.sharing.kutt.redis.secretName }}'
  data:
    - secretKey: '{{ .Values.sharing.kutt.redis.passwordKey }}'
      remoteRef:
        key: 'Storage/DragonFly/CoRE/Creds'
        property: 'Password'
{{- end }}
