apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: openemr-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - name: ingress-gw
  hostnames:
    - 'emr.mylogin.space'
  rules:
    - backendRefs:
        - name: k0s-cntrl-business-medical-openemr   
          port: 80