# {{- if .Values.secrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "automation.fullname" . }}-psql

  annotations:
    argocd.argoproj.io/sync-wave: '5'

spec:
  {{- with .Values.secrets.secretStoreRef }}
  secretStoreRef:
    {{- toYaml . | nindent 4  }}
  {{- end }}

  target:
    name: n8n-core-psql-secret

  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.secrets.rootPrefix }}/Credentials
        property: Password
# {{- end }}