apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "automation.fullname" . }}-redis

spec:
  refreshInterval: '30s'
  secretStoreRef:
    kind: ClusterSecretStore
    name: corevault-rootsecrets

  target:
    name: n8n-core-redis-secret

  data:
    - secretKey: redis-password
      remoteRef:
        key: Storage/DragonFly/CoRE/Creds
        property: Password
