{{- if .Values.freeswitch.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-freeswitch-rtp

  annotations:
    purelb.io/allow-shared-ip: main-gw.resolvemy.host
    purelb.io/service-group: main-public
    purelb.io/allow-local: 'true'

spec:
  type: LoadBalancer
  loadBalancerClass: purelb.io/purelb

  ports:
    - name: sip-udp
      port: 5060
      protocol: UDP
      targetPort: 5080

    - name: sip-tcp
      port: 5060
      protocol: TCP
      targetPort: 5080


{{- range untilStep (.Values.freeswitch.rtp.min|int) (.Values.freeswitch.rtp.max|int) 1 }}
    - port: {{ . }}
      nodeport: {{ . }}
      targetPort: {{ . }}
      protocol: UDP
      name: 'udp-{{ . }}'
{{ end }}

  selector:
    app: {{ $fullName }}-freeswitch
{{- end }}