{{- if .Values.freeswitch.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-freeswitch-dialplan-configs

  labels:
    app.kubernetes.io/name: {{ $fullName }}-freeswitch
data:
  public.xml: |
    <include>
      <context name="public">
        <extension name="flowroute-did">
          <condition field="destination_number" expression="^{{ $.Values.freeswitch.did }}$">
            <action application="set" data="outside_call=true"/>
            <action application="log" data="INFO AVoIP DID ${destination_number}: received call"/>
{{- if $.Values.freeswitch.preBridgeAudio.enabled }}
            <action application="answer"/>
            <action application="playback" data="shouts://{{ trimPrefix "https://" $.Values.freeswitch.preBridgeAudio.url }}"/>
            <action application="log" data="INFO AVoIP DID ${destination_number}: pre-bridge audio completed"/>
{{- end }}
            <action application="log" data="INFO AVoIP DID ${destination_number}: bridging to Asterisk"/>
            <action application="bridge" data="sofia/gateway/asterisk/${destination_number}"/>
          </condition>
        </extension>
      </context>
    </include>

  default.xml: |
    <include>
      <context name="default"/>
    </include>
{{- end }}
