{{- if .Values.freeswitch.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
{{- $terraformProvider := default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.freeswitch.cdr.terraformProvider -}}
{{- $crossplaneProvider := default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.freeswitch.cdr.crossplaneProvider -}}
---
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ $fullName }}-freeswitch

spec:
  name: 'FreeSwitch'
  serviceAccount: true
  groups:
    - 'LDAPService'
{{- if .Values.freeswitch.cdr.enabled }}
  psql:
    enabled: true
    crossplane:
      terraformProvider: '{{ $terraformProvider }}'
      crossplaneProvider: '{{ $crossplaneProvider }}'
{{- end }}

  writeConnectionSecretToRef:
    name: '{{ $fullName }}-freeswitch'
{{- end }}
