{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-freeswitch-upstream

data:
  flowroute.xml: |{{`
    <include>
      <gateway name="flowroute">
          <param name="username" value="{{ .Username }}" />
          <param name="auth-username" value="{{ .Username }}" />
          <param name="password" value="{{ .Password }}" />
          <param name="proxy" value="us-west-or.sip.flowroute.com" />
          <param name="expire-seconds" value="600" />
          <param name="register" value="true" />
          <param name="retry-seconds" value="30" />
          <param name="ping" value="25" />
      </gateway>
    </include>`}}