{{- if .Values.freeswitch.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-freeswitch-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: {{ $fullName }}-freeswitch-secrets

  data:
    - secretKey: Password
      remoteRef:
        key: AVoIP/FreeSwitch/Misc
        property: Password
{{- end }}