{{- if and .Values.freeswitch.enabled .Values.freeswitch.publicExposure.enabled .Values.freeswitch.publicExposure.sip.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: {{ $fullName }}-freeswitch

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ $.Values.gateway.namespace }}
      name: {{ $.Values.gateway.name }}
      sectionName: sip-udp

  rules:
    - backendRefs:
      - name: {{ $fullName }}-freeswitch
        port: 5060
{{- end }}
