{{- if .Values.freeswitch.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-ext-freeswitch

  labels:
    app.kubernetes.io/name: {{ $fullName }}-freeswitch
spec:
  type: ClusterIP

  ports:
    - name: tcp-sip
      port: 5060
      protocol: TCP
      targetPort: tcp-sipext

    - name: udp-sip
      port: 5060
      protocol: UDP
      targetPort: udp-sipext

    - name: tls-sips
      port: 5061
      protocol: TCP
      targetPort: tls-sipext
  selector:
    app.kubernetes.io/name: {{ $fullName }}-freeswitch
{{- end }}