{{- if .Values.freeswitch.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
{{- $freeswitchRtpEnd := .Values.freeswitch.rtp.max -}}
{{- if and .Values.rtpengine.enabled .Values.kamailio.enabled }}
{{- $freeswitchRtpEnd = sub (.Values.rtpengine.media.max | int) 1 -}}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-freeswitch-configs

data:
  freeswitch.xml: |
    <?xml version="1.0"?>
    <document type="freeswitch/xml">
      <X-PRE-PROCESS cmd="include" data="vars.xml"/>
      <section name="configuration" description="FreeSWITCH configuration">
        <X-PRE-PROCESS cmd="include" data="autoload_configs/*.xml"/>
      </section>
      <section name="dialplan" description="XML dialplan">
        <X-PRE-PROCESS cmd="include" data="dialplan/*.xml"/>
      </section>
      <section name="chatplan" description="SIP messaging">
        <X-PRE-PROCESS cmd="include" data="chatplan/*.xml"/>
      </section>
      <section name="directory" description="LDAP directory">
        <X-PRE-PROCESS cmd="include" data="directory/*.xml"/>
      </section>
    </document>

  vars.xml: |
    <include>
      <X-PRE-PROCESS cmd="env-set" data="default_password=${PASSWORD}"/>
      <X-PRE-PROCESS cmd="env-set" data="username=$USERNAME"/>
      <X-PRE-PROCESS cmd="env-set" data="password=$PASSWORD"/>
      <X-PRE-PROCESS cmd="set" data="domain=$${local_ip_v4}"/>
      <X-PRE-PROCESS cmd="set" data="domain_name=$${domain}"/>
      <X-PRE-PROCESS cmd="set" data="use_profile=external"/>
      <X-PRE-PROCESS cmd="set" data="external_rtp_ip={{ if and $.Values.rtpengine.enabled $.Values.kamailio.enabled }}$${local_ip_v4}{{ else if $.Values.freeswitch.publicExposure.enabled }}{{ $.Values.freeswitch.publicExposure.address }}{{ else }}{{ $.Values.network.externalIP }}{{ end }}"/>
      <X-PRE-PROCESS cmd="set" data="external_sip_ip={{ $.Values.network.egressIP }}"/>
      <X-PRE-PROCESS cmd="set" data="global_codec_prefs=OPUS,G722,PCMU,PCMA"/>
      <X-PRE-PROCESS cmd="set" data="outbound_codec_prefs=OPUS,G722,PCMU,PCMA"/>
      <X-PRE-PROCESS cmd="set" data="internal_sip_port=5060"/>
      <X-PRE-PROCESS cmd="set" data="internal_tls_port=5061"/>
      <X-PRE-PROCESS cmd="set" data="external_sip_port=5080"/>
      <X-PRE-PROCESS cmd="set" data="external_tls_port=5081"/>
      <X-PRE-PROCESS cmd="set" data="external_ssl_enable=true"/>
      <X-PRE-PROCESS cmd="set" data="sip_tls_version=tlsv1.2"/>
      <X-PRE-PROCESS cmd="set" data="sip_tls_ciphers=ALL:!ADH:!LOW:!EXP:!MD5:@STRENGTH"/>
      <X-PRE-PROCESS cmd="set" data="rtp-start-port={{ $.Values.freeswitch.rtp.min }}"/>
      <X-PRE-PROCESS cmd="set" data="rtp-end-port={{ $freeswitchRtpEnd }}"/>
      <X-PRE-PROCESS cmd="set" data="rtp_sdes_suites=AEAD_AES_256_GCM_8|AEAD_AES_128_GCM_8|AES_CM_128_HMAC_SHA1_80"/>
      <X-PRE-PROCESS cmd="set" data="console_loglevel=info"/>
      <X-PRE-PROCESS cmd="set" data="hold_music=silence_stream://2000"/>
      <X-PRE-PROCESS cmd="set" data="outbound_caller_name=FreeSWITCH"/>
      <X-PRE-PROCESS cmd="set" data="outbound_caller_id=0000000000"/>
    </include>
{{- end }}
