{{- if .Values.freeswitch.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-freeswitch-misc-configs

data:
  ldap.conf.xml: |
    <configuration name="xml_ldap.conf" description="LDAP directory gateway">
      <bindings>
        <binding name="directory">
          <param name="filter" value="(&amp;(objectClass=user)(cn=%s))" bindings="directory"/>
          <param name="basedn" value="ou=%s,ou=users,dc=ldap,dc=mylogin,dc=space"/>
          <param name="url" value="ldaps://ldap.mylogin.space"/>
          <param name="binddn" value="cn=$${username},ou=users,dc=ldap,dc=mylogin,dc=space"/>
          <param name="bindpass" value="$${password}"/>
          <trans>
            <tran name="id" mapfrom="uid"/>
            <tran name="cidr" mapfrom="fsCIDR"/>
            <tran name="number-alias" mapfrom="fsNumberAlias"/>
            <tran name="dial-string" mapfrom="fsDialString"/>
            <tran name="password" mapfrom="fsPassword"/>
            <tran name="a1-hash" mapfrom="fsA1Hash"/>
            <tran name="user_context" mapfrom="fsUserContext"/>
            <tran name="callgroup" mapfrom="fsCallGroup"/>
            <tran name="effective_caller_id_number" mapfrom="fsEffectiveCallerIDNumber"/>
            <tran name="effective_caller_id_name" mapfrom="fsEffectiveCallerIDName"/>
          </trans>
        </binding>
      </bindings>
    </configuration>

  opus.conf.xml: |
    <configuration name="opus.conf">
      <settings>
        <param name="use-vbr" value="1"/>
        <param name="complexity" value="10"/>
        <param name="keep-fec-enabled" value="1"/>
        <param name="maxaveragebitrate" value="0"/>
        <param name="maxplaybackrate" value="0"/>
        <param name="mono" value="0"/>
      </settings>
    </configuration>

  modules.conf.xml: |
    <configuration name="modules.conf" description="Modules">
      <modules>
        <load module="mod_console"/>
        <load module="mod_logfile"/>
        <load module="mod_sofia"/>
        <load module="mod_xml_ldap"/>
        <load module="mod_sms_flowroute"/>
        <load module="mod_dialplan_xml"/>
        <load module="mod_dptools"/>
        <load module="mod_shout"/>
        <load module="mod_spandsp"/>
        <load module="mod_commands"/>
        <load module="mod_event_socket"/>
        <load module="mod_opus"/>
      </modules>
    </configuration>

  console.conf.xml: |
    <configuration name="console.conf" description="Console Logger">
      <mappings>
        <map name="all" value="console,debug,info,notice,warning,err,crit,alert"/>
      </mappings>
      <settings>
        <param name="colorize" value="false"/>
        <param name="log_event" value="DEBUG"/>
        <param name="all" value="DEBUG"/>
        <param name="loglevel" value="$${console_loglevel}"/>
      </settings>
    </configuration>

  switch.conf.xml: |
    <configuration name="switch.conf" description="Core Configuration">
      <settings>
        <param name="colorize-console" value="false"/>
        <param name="dialplan-timestamps" value="false"/>
        <param name="max-db-handles" value="50"/>
        <param name="db-handle-timeout" value="10"/>
        <param name="max-sessions" value="1000"/>
        <param name="sessions-per-second" value="30"/>
        <param name="loglevel" value="info"/>
        <param name="rtp-start-port" value="{{ .Values.freeswitch.rtp.min }}"/>
        <param name="rtp-end-port" value="{{ .Values.freeswitch.rtp.max }}"/>
        <param name="rtp-enable-zrtp" value="false"/>
      </settings>
    </configuration>

  logfile.conf.xml: |
    <configuration name="logfile.conf" description="File Logging">
      <settings>
        <param name="rotate-on-hup" value="true"/>
      </settings>
      <profiles>
        <profile name="default">
          <settings>
            <param name="logfile" value="/dev/stdout"/>
            <param name="rollover" value="0"/>
            <param name="uuid" value="true"/>
          </settings>
          <mappings>
            <map name="all" value="console,debug,info,notice,warning,err,crit,alert"/>
          </mappings>
        </profile>
      </profiles>
    </configuration>

  event_socket.conf.xml: |
    <configuration name="event_socket.conf" description="Event Socket">
      <settings>
        <param name="listen-ip" value="127.0.0.1"/>
        <param name="listen-port" value="8021"/>
        <param name="password" value="$${password}"/>
      </settings>
    </configuration>

  spandsp.conf.xml: |
    <configuration name="spandsp.conf" description="SpanDSP config">
      <fax-settings>
        <param name="use-ecm" value="true"/>
        <param name="verbose" value="false"/>
        <param name="enable-t38" value="true"/>
        <param name="enable-t38-request" value="true"/>
        <param name="ident" value="{{ $.Values.freeswitch.fax.ident }}"/>
        <param name="header" value="{{ $.Values.freeswitch.fax.header }}"/>
        <param name="spool-dir" value="{{ $.Values.freeswitch.fax.spoolPath }}"/>
        <param name="file-prefix" value="faxrx"/>
      </fax-settings>
    </configuration>

  acl.conf.xml: |
    <configuration name="acl.conf" description="Network Lists">
      <network-lists>
        <list name="asterisk" default="deny">
          <node type="allow" cidr="10.0.0.0/8"/>
        </list>
        <list name="flowroute" default="deny">
{{- range $.Values.freeswitch.flowroute.signalingCIDRs }}
          <node type="allow" cidr="{{ . }}"/>
{{- end }}
        </list>
      </network-lists>
    </configuration>

  sofia.conf.xml: |
    <configuration name="sofia.conf" description="Sofia Endpoint">
      <global_settings>
        <param name="log-level" value="0"/>
        <param name="debug-presence" value="0"/>
      </global_settings>
      <profiles>
        <X-PRE-PROCESS cmd="include" data="../sip_profiles/*.xml"/>
      </profiles>
    </configuration>
{{- end }}
