apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-communications-mattermost-db-sync
spec:
  refreshInterval: '5m'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-communications-mattermost-db
    template:
      engineVersion: v2
      data:
        # multiline string
        DB_CONNECTION_STRING: 'postgres://{{ .Username }}:{{ .Password }}@psql.service.dc1.kjdev:5432/{{ .DatabaseDatabase }}?sslmode=disable&connect_timeout=10
'
  data:
    - secretKey: DatabaseDatabase
      remoteRef:
        key: Mattermost
        property: DatabaseDatabase

    - secretKey: Username
      remoteRef:
        key: Mattermost
        property: DatabaseUsername

    - secretKey: Password
      remoteRef:
        key: Mattermost
        property: DatabasePassword

    - secretKey: GitLabClientID
      remoteRef:
        key: Mattermost
        property: GitLabClientID
      
    - secretKey: GitLabClientSecret
      remoteRef:
        key: Mattermost
        property: GitLabClientSecret
