apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-communications-s3-sync
spec:
  refreshInterval: '5m'
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-communications-s3

  data:
    - secretKey: S3Bucket
      remoteRef:
        key: Mattermost
        property: S3Bucket

    - secretKey: S3AccessKey
      remoteRef:
        key: Mattermost
        property: S3AccessKey
      
    - secretKey: S3SecretKey
      remoteRef:
        key: Mattermost
        property: S3SecretKey
