apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nextcloud-workers
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: worker
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
      app.kubernetes.io/instance: nextcloud-prod
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
        app.kubernetes.io/instance: nextcloud-prod
        app.kubernetes.io/name: nextcloud
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3