apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-vaultwarden-database-prod-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: business-vaultwarden-database-prod
    template:
      engineVersion: v2
      data:
        # multiline string
        DBURI: '{{`postgresql://{{ .Username }}:{{ .Password }}@{{ .Hostname }}:5432/{{ .Database }}`}}'

  data:
    - secretKey: Hostname
      remoteRef:
        key: Bitwarden/Database
        property: Hostname

    - secretKey: Database
      remoteRef:
        key: Bitwarden/Database
        property: Database

    - secretKey: Username
      remoteRef:
        key: Bitwarden/Database
        property: Username
      
    - secretKey: Password
      remoteRef:
        key: Bitwarden/Database
        property: Password
