apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: passwords-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'
    resolvemy.host/gw: '{{ .Values.gateway.name }}'
    resolvemy.host/gw-ns: '{{ .Values.gateway.namespace }}' 
    resolvemy.host/security: 'public'
    resolvemy.host/env: '{{ .Values.env }}'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Values.gateway.name }}
      name: {{ .Values.gateway.name }}
      sectionName: {{ .Values.gateway.sectionName }}

  hostnames:
    - {{ .Values.gateway.domainName }}

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

      backendRefs:
        - group: ''
          kind: Service
          name: dc1-k3s-node1-business-passwords-vaultwarden
          port: 80
          weight: 1

      timeouts:
        backendRequest: 120s
        request: 120s