apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-vaultwarden-mail-prod-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core




  target:
    name: business-vaultwarden-mail-prod

  data:
    - secretKey: Hostname
      remoteRef:
        key: Bitwarden/Mail
        property: Hostname

    - secretKey: Port
      remoteRef:
        key: Bitwarden/Mail
        property: Port

    - secretKey: Username
      remoteRef:
        key: Bitwarden/Mail
        property: Username
      
    - secretKey: Password
      remoteRef:
        key: Bitwarden/Mail
        property: Password
