{{- $fullName := include "common.names.fullname" . -}}
---
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ $fullName }}

spec:
  name: Vaultwarden

  psql:
    uri: postgresql://

  database:
    name: bitwarden

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ $fullName }}
