{{- if and .Values.vaultwarden.user.enabled (eq .Values.cluster.name .Values.vaultwarden.user.hubCluster) }}
---
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ .Values.vaultwarden.user.name | quote }}

spec:
  name: 'Vaultwarden'

  username: {{ .Values.vaultwarden.user.username | quote }}

  psql:
    enabled: true
    createUserDatabase: false

    databases:
      - {{ .Values.vaultwarden.psql.database | quote }}

    crossplane:
      crossplaneProvider: {{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.vaultwarden.psql.crossplaneProvider | quote }}
      terraformProvider: {{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.vaultwarden.psql.terraformProvider | quote }}

  groups:
    - 'LDAPService'

  writeConnectionSecretToRef:
    name: {{ .Values.vaultwarden.user.connectionSecretName | quote }}
{{- end }}
