{{- $isHub := eq .Values.cluster.name .Values.vaultwarden.user.hubCluster -}}
{{- if and .Values.vaultwarden.credentialsSync.enabled $isHub .Values.vaultwarden.user.enabled }}
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-push" .Values.vaultwarden.user.connectionSecretName | quote }}

  annotations:
    argocd.argoproj.io/sync-wave: '5'

spec:
  refreshInterval: {{ .Values.vaultwarden.credentialsSync.refreshInterval | quote }}
  updatePolicy: Replace
  deletionPolicy: None

  secretStoreRefs:
    - {{- toYaml .Values.vaultwarden.credentialsSync.secretStoreRef | nindent 6 }}

  selector:
    secret:
      name: {{ .Values.vaultwarden.user.connectionSecretName | quote }}

  data:
    - match:
        secretKey: 'username'
        remoteRef:
          remoteKey: {{ .Values.vaultwarden.credentialsSync.remoteKey | quote }}
          property: 'Username'

    - match:
        secretKey: 'password'
        remoteRef:
          remoteKey: {{ .Values.vaultwarden.credentialsSync.remoteKey | quote }}
          property: 'Password'

    - match:
        secretKey: 'database'
        remoteRef:
          remoteKey: {{ .Values.vaultwarden.credentialsSync.remoteKey | quote }}
          property: 'Database'
{{- else if and .Values.vaultwarden.credentialsSync.enabled (not $isHub) }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-pull" .Values.vaultwarden.user.connectionSecretName | quote }}

  annotations:
    argocd.argoproj.io/sync-wave: '5'

spec:
  refreshInterval: {{ .Values.vaultwarden.credentialsSync.refreshInterval | quote }}

  secretStoreRef:
    {{- toYaml .Values.vaultwarden.credentialsSync.secretStoreRef | nindent 4 }}

  target:
    name: {{ .Values.vaultwarden.user.connectionSecretName | quote }}
    creationPolicy: Orphan
    deletionPolicy: Retain

  data:
    - secretKey: 'username'
      remoteRef:
        key: {{ .Values.vaultwarden.credentialsSync.remoteKey | quote }}
        property: 'Username'

    - secretKey: 'password'
      remoteRef:
        key: {{ .Values.vaultwarden.credentialsSync.remoteKey | quote }}
        property: 'Password'

    - secretKey: 'database'
      remoteRef:
        key: {{ .Values.vaultwarden.credentialsSync.remoteKey | quote }}
        property: 'Database'
{{- end }}
