apiVersion: v2
version: 1.0.0
name: medical-core

dependencies:
  #
  # OpenEMR
  #
  - name: openemr
    version: 5.2.0
    repository: https://geek-cookbook.github.io/charts/
    condition: openemr.enabled
