global:
  createDefaultServiceAccount: true

gateway:
  name: 'main-gw'
  namespace: 'core-prod'
  sectionName: 'https-myloginspace'

itTools:
  domain: 'it-tools.mylogin.space'
  replicas: 2

  image:
    repository: 'ghcr.io/corentinth/it-tools'
    tag: '2024.10.22-7ca5933'
    digest: 'sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f'
    pullPolicy: 'IfNotPresent'

  resources:
    requests:
      cpu: '25m'
      memory: '64Mi'
    limits:
      cpu: '500m'
      memory: '256Mi'
