apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-db-prod-sync
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: vikunja-db-prod-sync

  data:
    - secretKey: DatabaseDatabase
      remoteRef:
        key: Vikunja
        property: DatabaseDatabase

    - secretKey: DatabasePassword
      remoteRef:
        key: Vikunja
        property: DatabasePassword

    - secretKey: DatabaseUsername
      remoteRef:
        key: Vikunja
        property: DatabaseUsername

