apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja-jwt-prod-sync
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: vikunja-jwt-prod

  data:
    - secretKey: SecretKey
      remoteRef:
        key: Vikunja
        property: SecretKey

