apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k0s-cntrl-erpnext
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: infra1-storage
  volumeMode: Filesystem
