apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: collabora-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: core-prod
      name: main-gw
      sectionName: https

  hostnames:
    - 'collabora.mylogin.space'
  rules:
    - backendRefs:
        - name: k0s-cntrl-business-office-collabora-code
          port: 9980