apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-office-nextcloud-database-prod-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-office-nextcloud-database-prod

  data:
    - secretKey: Database
      remoteRef:
        key: Nextcloud/Database
        property: Database

    - secretKey: Username
      remoteRef:
        key: Nextcloud/Database
        property: Username
      
    - secretKey: Password
      remoteRef:
        key: Nextcloud/Database
        property: Password
