apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: office-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: kuadrant-core-prod
      name: main-gw

  hostnames:
    - 'office.mylogin.space'
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/carddav

        - path:
            type: PathPrefix
            value: /.well-known/caldav

      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /nextcloud/remote.php/dav
            statusCode: 301


    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/webfinger

      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /nextcloud/index.php/.well-known/webfinger
            statusCode: 301


    - matches:
        - path:
            type: PathPrefix
            value: /.well-known/nodeinfo

      filters:
        - type: RequestRedirect
          requestRedirect:
            path:
              type: ReplaceFullPath
              replaceFullPath: /nextcloud/index.php/.well-known/nodeinfo 
            statusCode: 301

    - backendRefs:
        - name: dc1-k3s-node1-business-office-nextcloud
          port: 8080