apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-edit
spec:
  replicas: 1

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: pdf-edit-ui

  template:
    metadata:
      labels:
        app: pdf-edit-ui

    spec:
    #   securityContext:
    #     runAsUser: 1000
    #     runAsNonRoot: true
    #     runAsGroup: 1000
    #     fsGroup: 1000

      containers:
        - image: frooodle/s-pdf
          name: pdf-edit-ui
          env:
            - name: SERVER_PORT
              value: '8080'
        #   securityContext:
        #     readOnlyRootFilesystem: true

          ports:
            - name: http
              containerPort: 8080
