apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pdf-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: core-prod
      name: main-gw
      sectionName: https

  hostnames:
    - 'pdf.mylogin.space'
  rules:
    - backendRefs:
        - name: pdf-edit-ui
          port: 80