{{- if .Values.asterisk.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
{{- $cdrHost := default (printf "psql-local.%s.%s.%s.mylogin.space" .Values.cluster.name .Values.datacenter .Values.region) .Values.asterisk.cdr.host -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-asterisk-configs

data:
  asterisk.conf: |
    [options]
    languageprefix=yes
    entityid={{ .Values.asterisk.entityID }}
    systemname=avoip-asterisk

  modules.conf: |
    [modules]
    autoload=yes
    require = chan_pjsip.so
    require = res_http_media_cache.so
    noload => chan_iax2.so
    noload => chan_alsa.so
    noload => chan_mobile.so
    noload => app_adsiprog.so
    noload => app_getcpeid.so
    noload => res_adsi.so
    noload => res_config_ldap.so
    noload => res_config_pgsql.so
    noload => res_pjsip_phoneprov_provider.so
    noload => res_phoneprov.so
    noload => res_musiconhold.so
    noload => res_smdi.so
    {{- if .Values.asterisk.cdr.enabled }}
    require = cdr_pgsql.so
    {{- else }}
    noload => cdr_pgsql.so
    {{- end }}
    noload => cdr_csv.so
    noload => cdr_custom.so
    noload => cdr_sqlite3_custom.so
    noload => cel_custom.so
    noload => cel_sqlite3_custom.so
    noload => cel_pgsql.so
    noload => res_hep.so
    noload => res_hep_pjsip.so
    noload => res_hep_rtcp.so
    noload => chan_sip.so
    noload => app_voicemail_imap.so
    noload => app_voicemail_odbc.so
    noload => app_fax.so
    noload => app_faxdetect.so
    noload => res_fax.so
    noload => res_fax_spandsp.so

  logger.conf: |
    [general]

    [logfiles]
    console => notice,warning,error,verbose,debug
    messages.log => notice,warning,error

  cdr.conf: |
    [general]
    enable=yes
    batch=yes
    safeshutdown=yes

  cdr_pgsql.conf: |
    #include /tmp/avoip-cdr_pgsql.conf

  rtp.conf: |
    [general]
    rtpstart={{ .Values.asterisk.rtp.min }}
    rtpend={{ .Values.asterisk.rtp.max }}
    icesupport=true

  extensions.conf: |
    [general]
    static=yes
    writeprotect=no
    clearglobalvars=no

    [from-external]
    exten => 18077893501,1,Answer()
      same => n,Playback(demo-echodone)
      same => n,Echo()
      same => n,Hangup()
{{- end }}
