{{- if and .Values.asterisk.enabled .Values.asterisk.turn.enabled }}
{{- $secretName := .Values.asterisk.turn.secret.name -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secretName | quote }}
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.asterisk.turn.secret.secretStoreRef | nindent 4 }}
  target:
    name: {{ $secretName | quote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'TURN_SHARED_SECRET'
      remoteRef:
        key: {{ .Values.asterisk.turn.secret.remoteKey | quote }}
        property: {{ .Values.asterisk.turn.secret.remoteProperty | quote }}
{{- end }}
