{{- if and .Values.asterisk.enabled .Values.asterisk.sipCore.enabled }}
{{- $root := . -}}
{{- range .Values.asterisk.sipCore.extensions }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ include "avoip.asterisk.sipCore.secretName" (dict "root" $root "number" .number) }}'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    kind: '{{ $root.Values.asterisk.sipCore.secretStoreRef.kind }}'
    name: '{{ $root.Values.asterisk.sipCore.secretStoreRef.name }}'
  target:
    name: '{{ include "avoip.asterisk.sipCore.secretName" (dict "root" $root "number" .number) }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'password'
      remoteRef:
        key: '{{ .secret.remoteKey }}'
        property: '{{ .secret.property }}'
{{- end }}
{{- end }}
