{{- if and .Values.asterisk.enabled .Values.freeswitch.enabled }}
{{- $secretName := printf "%s-asterisk-freeswitch-peer" (include "avoip.fullname" .) -}}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: '{{ $secretName }}-generator'
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  length: 32
  digits: 0
  symbols: 0
  allowRepeat: true
  encoding: 'hex'
  secretKeys:
    - 'password'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ $secretName }}-generate'
  annotations:
    argocd.argoproj.io/sync-wave: '-9'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: '{{ $secretName }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: 'Password'
          name: '{{ $secretName }}-generator'
{{- end }}
