apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-projects-openproject-database-{{ .Values.secretSuffix }}-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-projects-openproject-database-{{ .Values.secretSuffix }}
    template:
      engineVersion: v2
      data:
        # multiline string
        DBURI: '{{`postgres://{{ .Username }}:{{ .Password }}@{{ .Hostname }}:{{ .Port }}}/{{ .Database }}`}}'
  data:
    - secretKey: Hostname
      remoteRef:
        key: OpenProject/Database
        property: Hostname

    - secretKey: Port
      remoteRef:
        key: OpenProject/Database
        property: Port

    - secretKey: Database
      remoteRef:
        key: OpenProject/Database
        property: Database

    - secretKey: Username
      remoteRef:
        key: OpenProject/Database
        property: Username

    - secretKey: Password
      remoteRef:
        key: OpenProject/Database
        property: Password
      


