apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: core-prod
      name: main-gw
      sectionName: https

  hostnames:
    - 'projects.mylogin.space'
  rules:
    - backendRefs:
        - name: openproject-svc
          port: 8080

