apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: business-projects-openproject-s3-{{ .Values.secretSuffix }}-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-projects-openproject-s3-{{ .Values.secretSuffix }}
  data:
    - secretKey: Bucket 
      remoteRef:
        key: OpenProject/S3
        property: Bucket

    - secretKey: AccessKey
      remoteRef:
        key: OpenProject/S3
        property: AccessKey
      
    - secretKey: SecretKey
      remoteRef:
        key: OpenProject/S3
        property: SecretKey

