apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-projects-openproject-s3-{{ .Values.secretSuffix }}-sync
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-projects-openproject-s3-{{ .Values.secretSuffix }}
  data:
    - secretKey: S3Bucket
      remoteRef:
        key: OpenProject
        property: S3Bucket

    - secretKey: S3AccessKey
      remoteRef:
        key: OpenProject
        property: S3AccessKey
      
    - secretKey: S3SecretKey
      remoteRef:
        key: OpenProject
        property: S3SecretKey

