blink:
  enabled: true

  publicURI: snd.fyi

  clusterDomain: k0s.resolvemy.host

  istio:
    gateway: ingressgateway

  image:
    repository: ghcr.io/janejeon/blink
    tag: latest
    pullPolicy: Always
    pullSecrets: []

  replicaCount: 1

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

  certSANs:
    dnsNames: []
    ipAddresses: []

  extraArgs: {}

  labels: {}
  annotations: {}
  podLabels: {}
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  podAntiAffinity: soft
  podAntiAffinityTopologyKey: kubernetes.io/hostname
  affinity: {}

  extraEnv:
    - name: OIDC_ISSUER_BASE_URL
      value: https://idp.mylogin.space/application/o/Links/

    - name: OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: blink-links-server-secrets
          key: OpenIDClientID
          optional: false
 
  sidecars: []
  extraVolumes: []
  extraVolumeMounts: []


  port: 6443
  service:
    enabled: true
    type: ClusterIP # or LoadBalancer
    labels: {}
    annotations: {}
    loadBalancerIP: ''


xbackbone:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #
  publicURL: https://share.kjmedia.stream

  podAnnotations:
    sidecar.istio.io/inject: 'true'

  # -- Set labels on the pod
  podLabels:
    sidecar.istio.io/inject: 'true'

  controller:
    replicas: 0

  image:
    # -- image repository
    repository: thelaughingman/xbackbone
    tag: latest
    # -- image pull policy
    pullPolicy: Always

  # -- environment variables. See [image repo](https://github.com/Pe46dro/XBackBone-docker#environment-variables) for more details.
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: UTC

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 80

  configmap:
    config:
      # -- Enables or disables the configMap
      enabled: true
      # -- Labels to add to the configMap
      labels: {}
      # -- Annotations to add to the configMap
      annotations: {}
      # -- configMap data content. Helm template enabled.
      data:
        config.php: |



  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: false
      ingressClassName: traefik-core

      labels:
        wan-mode: 'public'
        lan-mode: 'private'

      annotations:
        cert-manager.io/cluster-issuer: kjdev-cluster
        external-dns.alpha.kubernetes.io/target: k0s-dc1.resolvemy.host.
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
      hosts:
        -  # -- Host address. Helm template can be passed.
          host: share.kjmedia.stream
          ## Configure the paths for the host
          paths:
            -  # -- Path.  Helm template can be passed.
              path: /
              # -- Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix

      tls:
        - secretName: kjmediastream-default-certificates
          hosts:
            - '*.kjmedia.stream'

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      # -- Enables or disables the persistence item
      enabled: false

      # -- Sets the persistence type
      # Valid options are pvc, emptyDir, hostPath, secret, configMap or custom
      type: secret



      # -- Where to mount the volume in the main container.
      # Defaults to `/<name_of_the_volume>`,
      # setting to '-' creates the volume but disables the volumeMount.
      mountPath: /app/random.php
      # -- Specify if the volume should be mounted read-only.
      readOnly: false
      # -- Override the name suffix that is used for this volume.
      name: business-sharing-xbackbone-config

      # -- Used in conjunction with `existingClaim`. Specifies a sub-path inside the referenced volume instead of its root
      subPath: config.php

    phpconfig:
      # -- Enables or disables the persistence item
      enabled: false

      # -- Sets the persistence type
      # Valid options are pvc, emptyDir, hostPath, secret, configMap or custom
      type: configMap



      # -- Where to mount the volume in the main container.
      # Defaults to `/<name_of_the_volume>`,
      # setting to '-' creates the volume but disables the volumeMount.
      mountPath: /config/php/php-local.ini
      # -- Specify if the volume should be mounted read-only.
      readOnly: false
      # -- Override the name suffix that is used for this volume.
      name: business-sharing-xbackbone-php-config

      # -- Used in conjunction with `existingClaim`. Specifies a sub-path inside the referenced volume instead of its root
      subPath: php-local.ini

    data:
      enabled: true
      mountPath: /app
      accessMode: ReadWriteOnce

      type: pvc

      # -- The amount of storage that is requested for the persistent volume.
      size: 1Gi

      nameOverride: xbackbone-data

      # -- Set to true to retain the PVC upon `helm uninstall`
      retain: false
