{{- if include "avoip.talkHpb.enabled" . | trim }}
{{- $talkHpb := .Values.talkHpb }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: '{{ $talkHpb.secrets.generatorName }}'
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  length: 64
  digits: 0
  symbols: 0
  allowRepeat: true
  encoding: 'hex'
  secretKeys:
    - 'SIGNALING_SECRET'
    - 'INTERNAL_SECRET'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ $talkHpb.secrets.bootstrapName }}-generate'
  annotations:
    argocd.argoproj.io/sync-wave: '-9'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: '{{ $talkHpb.secrets.bootstrapName }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: 'Password'
          name: '{{ $talkHpb.secrets.generatorName }}'
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: '{{ $talkHpb.secrets.name }}-push'
  annotations:
    argocd.argoproj.io/sync-wave: '-8'
spec:
  refreshInterval: '1h'
  updatePolicy: 'Replace'
  deletionPolicy: 'None'
  secretStoreRefs:
    - kind: '{{ $talkHpb.turn.secretStoreRef.kind }}'
      name: '{{ $talkHpb.turn.secretStoreRef.name }}'
  selector:
    secret:
      name: '{{ $talkHpb.secrets.bootstrapName }}'
  data:
    - match:
        secretKey: 'SIGNALING_SECRET'
        remoteRef:
          remoteKey: '{{ $talkHpb.secrets.remoteKey }}'
          property: 'SignalingSecret'
    - match:
        secretKey: 'INTERNAL_SECRET'
        remoteRef:
          remoteKey: '{{ $talkHpb.secrets.remoteKey }}'
          property: 'InternalSecret'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ $talkHpb.secrets.name }}'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    kind: '{{ $talkHpb.turn.secretStoreRef.kind }}'
    name: '{{ $talkHpb.turn.secretStoreRef.name }}'
  target:
    name: '{{ $talkHpb.secrets.name }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'SIGNALING_SECRET'
      remoteRef:
        key: '{{ $talkHpb.secrets.remoteKey }}'
        property: 'SignalingSecret'
    - secretKey: 'INTERNAL_SECRET'
      remoteRef:
        key: '{{ $talkHpb.secrets.remoteKey }}'
        property: 'InternalSecret'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ $talkHpb.secrets.turnName }}'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    kind: '{{ $talkHpb.turn.secretStoreRef.kind }}'
    name: '{{ $talkHpb.turn.secretStoreRef.name }}'
  target:
    name: '{{ $talkHpb.secrets.turnName }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'TURN_SECRET'
      remoteRef:
        key: '{{ $talkHpb.turn.remoteKey }}'
        property: '{{ $talkHpb.turn.remoteProperty }}'
{{- end }}
