apiVersion: v1
kind: ConfigMap
metadata:
  name: 'business-mail-rspamd-dragonfly-tpl'
data:
  redis.conf: |
    servers = "{{ .Values.site.dragonfly.hostname }}:{{ .Values.site.dragonfly.port }}";
    db = "{{ .Values.site.dragonfly.database }}";
    password = "{{`{{ .Password }}`}}";
    use_ssl = true;
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: 'business-mail-rspamd-dragonfly'
spec:
  refreshInterval: '30s'
  secretStoreRef:
    kind: {{ .Values.site.dragonfly.secretStoreRef.kind | quote }}
    name: {{ .Values.site.dragonfly.secretStoreRef.name | quote }}
  target:
    name: 'business-mail-rspamd-dragonfly'
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: 'business-mail-rspamd-dragonfly-tpl'
            items:
              - key: 'redis.conf'
  data:
    - secretKey: 'Password'
      remoteRef:
        key: {{ .Values.site.dragonfly.remoteRef.key | quote }}
        property: {{ .Values.site.dragonfly.remoteRef.passwordProperty | quote }}
