{{- $values := index .Values "collabora-online" }}
{{- $chart := index $.Subcharts "collabora-online" }}
{{- if $values.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: collabora-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Values.gateway.namespace }}
      name: {{ .Values.gateway.name }}
      sectionName: {{ .Values.gateway.sectionName }}

  hostnames:
    - {{ $values.domain }}
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: {{ include "collabora-online.fullname" $chart }}
          port: {{ $values.service.port }}
          weight: 1

      timeouts:
        request: 300s
        backendRequest: 300s
{{- end }}