{{- $values := index .Values "collabora-online" }}
{{- if $values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: collabora-runtime
  labels:
    app.kubernetes.io/name: collabora-online
    app.kubernetes.io/instance: {{ .Release.Name }}
automountServiceAccountToken: false
{{- end }}
