{{- if .Values.simplelogin.enabled }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ .Release.Name }}-simplelogin

spec:
  name: SimpleLogin

  database:
    name: simplelogin

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ .Release.Name }}-simplelogin
{{- end }}