{{- if .Values.simplelogin.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: business-mail-simplelogin-db-prod-sync
spec:
  secretStoreRef:
    {{- toYaml .Values.credentialsSync.secretStoreRef | nindent 4 }}

  target:
    name: business-mail-simplelogin-db-prod
    template:
      engineVersion: v2
      data:
        DB_URI: '{{`postgresql://{{ .Username }}:{{ .Password }}@`}}{{ .Values.site.psql.hostname }}:{{ .Values.site.psql.port }}{{`/{{ .Database }}`}}'

        URL: 'https://simplelogin.mylogin.space'

  data:
    - secretKey: Database
      remoteRef:
        key: {{ include "mail.credentialsRemoteKey" (dict "root" . "name" "SimpleLogin/Database") | quote }}
        property: Database

    - secretKey: Username
      remoteRef:
        key: {{ include "mail.credentialsRemoteKey" (dict "root" . "name" "SimpleLogin/Database") | quote }}
        property: Username

    - secretKey: Password
      remoteRef:
        key: {{ include "mail.credentialsRemoteKey" (dict "root" . "name" "SimpleLogin/Database") | quote }}
        property: Password
{{- end }}
