{{- if .Values.simplelogin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplelogin-mailhandler
  labels:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: mailhandler
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: simplelogin
      app.kubernetes.io/component: mailhandler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simplelogin
        app.kubernetes.io/component: mailhandler
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: 
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In 
                    values:
                      - simplelogin 
              topologyKey: kubernetes.io/hostname
      volumes:
        - name: simplelogin-data
          persistentVolumeClaim:
            claimName: simplelogin-data

        - name: config-env
          secret:
            secretName: business-mail-simplelogin-db-prod

        - name: dkim-public
          configMap:
            name: simplelogin-dkim-public-cert
            items:
              - key: dkim.pub.key
                path: dkim.pub.key

        - name: dkim-secrets
          secret:
            secretName: selector1-mail-myloginspace
            items:
            - key: mail.mylogin.space.selector1.key
              path: dkim.key

      containers:
        - name: simplelogin
          image: simplelogin/app:3.4.0
          command: ['python']
          args: ['email_handler.py']

          envFrom:
            - secretRef:
                name: business-mail-simplelogin-db-prod

            - configMapRef:
                name: simplelogin-config

          ports:
            - containerPort: 20381
              name: smtp

          volumeMounts:
            - mountPath: /code/static/upload
              name: simplelogin-data

            - mountPath: /code/.env
              name: config-env
              subPath: SLENV

            - mountPath: /secret/dkim.key
              name: dkim-secrets
              subPath: dkim.key

            - mountPath: /secret/dkim.pub.key
              name: dkim-public
              subPath: dkim.pub.key
{{- end }}