{{- if .Values.simplelogin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: simplelogin-api
spec:
  selector:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
{{- end }}