{{- if .Values.simplelogin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: simplelogin-mailhandler
spec:
  selector:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: mailhandler
  ports:
    - protocol: TCP
      port: 20381
      targetPort: smtp
{{- end }}