{{- if and .Values.simplelogin.enabled (eq (include "mail.managesCredentials" .) "true") }}
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ .Release.Name }}-simplelogin

spec:
  name: 'SimpleLogin'

  psql:
    enabled: true
    createUserDatabase: false
    databases:
      - 'simplelogin'
    crossplane:
      crossplaneProvider: {{ .Values.site.psql.crossplaneProvider | quote }}
      terraformProvider: {{ .Values.site.psql.terraformProvider | quote }}

  groups:
    - 'LDAPService'

  writeConnectionSecretToRef:
    name: {{ printf "%s-simplelogin" .Release.Name | quote }}
{{- end }}
