{{- .Values.dns.automagic.enabled }}
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: mail

  labels:
    wan-mode: public
    lan-mode: private

spec:
  endpoints:
    - dnsName: mylogin.space
      recordTTL: 180
      recordType: MX
      targets:
        - mail.mylogin.space
{{- end }}