apiVersion: v2
version: 1.0.0
name: knowledge-core

dependencies:
  #
  # People Management
  #
  - name: monica
    version: 8.2.0
    repository: https://geek-cookbook.github.io/charts/
    condition: monica.enabled

  #
  # Outline
  #
  - name: outline
    version: 6.0.23
    repository: https://charts.truecharts.org/