

outline:
  name: k0s-cntrl-business-knowledge-outline   

  image:
    repository: outlinewiki/outline
    pullPolicy: IfNotPresent
    tag: latest

  securityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: false

  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0

  env:
    FORCE_HTTPS: false
    PGSSLMODE: "disable"
    PORT: "{{ .Values.service.main.ports.main.port }}"
    # User defined
    URL: "https://outline.mylogin.space:443"
    SLACK_MESSAGE_ACTIONS: true
    ENABLE_UPDATES: true
    WEB_CONCURRENCY: 1
    MAXIMUM_IMPORT_SIZE: 5120000
    DEFAULT_LANGUAGE: "en_US"
    # TEAM_LOGO: ""
    # COLLABORATION_URL: ""
    # SLACK_KEY: ""
    # SLACK_SECRET: ""
    # SLACK_VERIFICATION_TOKEN: ""
    # SLACK_APP_ID: ""
    # GOOGLE_CLIENT_ID: ""
    # GOOGLE_CLIENT_SECRET: ""
    # GOOGLE_ANALYTICS_ID: ""
    # AZURE_CLIENT_ID: ""
    # AZURE_CLIENT_SECRET: ""
    # AZURE_RESOURCE_APP_ID: ""
    OIDC_CLIENT_ID:
      secretKeyRef:
        name: business-knowledge-outline-oidc
        key: OpenIDClientID

    OIDC_CLIENT_SECRET:
      secretKeyRef:
        name: business-knowledge-outline-oidc
        key: OpenIDClientSecret
    
    OIDC_AUTH_URI: https://idp.mylogin.space/application/o/authorize/
    OIDC_TOKEN_URI: https://idp.mylogin.space/application/o/token/
    OIDC_USERINFO_URI: https://idp.mylogin.space/application/o/userinfo/
    # OIDC_USERNAME_CLAIM: ""
    OIDC_DISPLAY_NAME: "Authentik"
    # OIDC_SCOPES: ""
    # SENTRY_DSN: ""
    AWS_ACCESS_KEY_ID:
      secretKeyRef:
        name: business-knowledge-outline-s3
        key: S3AccessKey
    
    AWS_SECRET_ACCESS_KEY:
      secretKeyRef:
        name: business-knowledge-outline-s3
        key: S3SecretAccessKey

    AWS_REGION: us-east-1

    # AWS_S3_ACCELERATE_URL: ""
    AWS_S3_UPLOAD_BUCKET_URL: https://s3.mylogin.space
    AWS_S3_UPLOAD_BUCKET_NAME:
      secretKeyRef:
        name: business-knowledge-outline-s3
        key: S3Bucket

    # AWS_S3_UPLOAD_MAX_SIZE: 26214400
    AWS_S3_FORCE_PATH_STYLE: true
    # AWS_S3_ACL: ""
    # SMTP_HOST: ""
    # SMTP_PORT: 587
    # SMTP_USERNAME: ""
    # SMTP_PASSWORD: ""
    # SMTP_FROM_EMAIL: ""
    # SMTP_REPLY_EMAIL: ""
    # SMTP_SECURE: true

    DATABASE_URL: 
      secretKeyRef:
        name: business-knowledge-outline-db
        key: DBURI

    REDIS_URL: redis://10.1.1.68/100

    SECRET_KEY:
      secretKeyRef:
        name: business-knowledge-outline-misc
        key: SecretKey

    UTILS_SECRET:
      secretKeyRef:
        name: business-knowledge-outline-misc
        key: UtilsSecret

  service:
    main:
      ports:
        main:
          port: 10196

  probes:
    liveness:
      path: "/_health"
    readiness:
      path: "/_health"
    startup:
      path: "/_health"

  # Enabled redis
  redis:
    enabled: false

  # Enabled postgres
  postgresql:
    enabled: false

  minio:
    enabled: false

  initContainers:
    1-migratedb:
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: business-knowledge-outline-db
              key: DBURI

        - name: REDIS_URL
          value: redis://10.1.1.68/100

        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: business-knowledge-outline-misc
              key: SecretKey

        - name: UTILS_SECRET
          valueFrom:
            secretKeyRef:
              name: business-knowledge-outline-misc
              key: UtilsSecret

      command:
        ["sh", "-c", "yarn sequelize db:migrate --env=production-ssl-disabled"]

  portal:
    enabled: false
