

env: prod

hub: true

cluster:
  name: k8s
  domain: cluster.local

datacenter: dc1

region: yxl

global:
  test: 'test'

tts:
  enabled: true

mcpbox:
  enabled: true

  image: quay.io/mudler/localagi-mcpbox

  tag: main

localagi:
  enabled: true

  persistence:
    enabled: true

  image: quay.io/mudler/localagi
  tag: main


wyoming:
  enabled: true

  service:
    enabled: true

  image: ghcr.io/roryeckel/wyoming_openai
  tag: latest

  tts:
    endpoint: http://172.31.192.12:8880/v1

    models: 'tts-1-hd'

    voices: 'af_bella'

  logs:
    level: INFO

  languages: 'en'

speeches:
  enabled: true

  image: ghcr.io/speaches-ai/speaches
  tag: 0.8.0-rc.3-cuda-12.4.1

  runtimeClassName: nvidia

  nodeSelector:
    gpu-node: 'true'


externalSecrets:
  enabled: true

  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

gpustack:
  enabled: true

  nodeSelector:
    kubernetes.io/hostname: hpc1

localai:
  enabled: false

  nodeSelector:
    kubernetes.io/hostname: hpc3

docker:
  mcp:
    enabled: true
  kubedock:
    enabled: false

    rbac:
      create: false

llama:
  #
  # TODO: Test Servers with GRPC backends
  #
  server:
    enabled: true

  models: []
    # - name: qwen3-large
    #   container:
    #     image:
    #       repository: kristianfoss/llama
    #       tag: 'test'
    #       pullPolicy: Always
    
    #   path: /models/Qwen_Qwen3-30B-A3B-Q4_0.gguf
    #   contextSize: 2048
    #   threads: 12
    #   batchSize: 256

    # - name: qwen3-r1
    #   container:
    #     image:
    #       repository: kristianfoss/llama
    #       tag: 'test'
    #       pullPolicy: Always
    
    #   path: /models/deepseek-ai_DeepSeek-R1-0528-Qwen3-8B-Q8_0.gguf
    #   contextSize: 8192
    #   threads: 12
    #   batchSize: 512

    # - name: nsfw-chat
    #   container:
    #     image:
    #       repository: kristianfoss/llama
    #       tag: 'test'
    #       pullPolicy: Always
    
    #   path: /models/L3-Nymeria-Maid-8B.Q4_K_M.gguf
    #   contextSize: 8192
    #   threads: 6
    #   batchSize: 512

    # - name: small-router
    #   container:
    #     image:
    #       repository: kristianfoss/llama
    #       tag: 'test'
    #       pullPolicy: Always
    
    #   path: /models/Qwen_Qwen3-4B-Thinking-2507-Q8_0.gguf
    #   contextSize: 8192
    #   threads: 6
    #   batchSize: 512

owui:
  enabled: true

  psql:
    enabled: true

    host: psql.core-home1-talos-prod.home1.yvr.mylogin.space

  mcpo:
    enabled: true

mcp:
  enabled: true

  hub:
    enabled: true

  containers:
    - name: brave-search
      image: mcp/brave-search
      tag: latest

      env:
        - name: BRAVE_API_KEY
          valueFrom:
            secretKeyRef:
              name: '{{ include "bjw-s.common.lib.chart.names.fullname" $ }}-core-business-ai-brave-search'
              key: APIKey

        - name: BRAVE_MCP_TRANSPORT
          value: 'http'

  frr:
    enabled: true

  docker:
    enabled: true

  search:
    enabled: true

ai:
  namespace:
    name: core-ai-testing

    create: true

gateway:
  name: main-gw
  namespace: core-prod
  sectionName: https-myloginspace



oauth:
  indexKey: openwebui
  scopes: ''
  groups: []
  authentik:
    urlBase: https://idp.mylogin.space
