apiVersion: apps/v1
kind: Deployment
metadata:
  name: avatars
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: avatars-ui
  template:
    metadata:
      labels:
        app: avatars-ui
    spec:
      securityContext:
        runAsUser: 0
        runAsNonRoot: false
        runAsGroup: 0
        fsGroup: 0
      volumes:
        - name: config-py
          secret:
            secretName: business-avatars-config-prod

      containers:
        - image: kristianfjones/ivatar:main
          name: avatars-ui
          securityContext:
            readOnlyRootFilesystem: false
          volumeMounts:
            - name: config-py
              mountPath: /srv/ivatar/config.py
              subPath: config.py
              readOnly: true

          env:
            - name: SECURE_BASE_URL
              value: 'https://avatar.mylogin.space'

            - name: S3AccessKey
              valueFrom:
                secretKeyRef:
                  name: business-avatars-s3-prod
                  key: S3AccessKey
          ports:
            - name: http
              containerPort: 8080
