apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-avatars-s3-prod-sync
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-avatars-s3-prod

  data:
    - secretKey: S3AccessKey
      remoteRef:
        key: Avatars/S3
        property: AccessKey
      
    - secretKey: S3SecretKey
      remoteRef:
        key: Avatars/S3
        property: SecretKey
