apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-avatars-s3-prod-sync
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-avatars-s3-prod

  data:
    - secretKey: S3AccessKey
      remoteRef:
        key: Avatar
        property: S3AccessKey
      
    - secretKey: S3SecretKey
      remoteRef:
        key: Avatar
        property: S3SecretKey
