apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: 'airtrail-database-user'
spec:
  name: 'AirTrail database'
  psql:
    enabled: true
    createUserDatabase: true
    crossplane:
      crossplaneProvider: '{{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.airtrail.database.crossplaneProvider }}'
      terraformProvider: '{{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.airtrail.database.terraformProvider }}'
  writeConnectionSecretToRef:
    name: '{{ .Values.airtrail.database.userSecret }}'
