apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: 'adventurelog-database-user'
spec:
  name: 'AdventureLog database'
  psql:
    enabled: true
    createUserDatabase: true
    crossplane:
      crossplaneProvider: '{{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.adventurelog.database.crossplaneProvider }}'
      terraformProvider: '{{ default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.adventurelog.database.terraformProvider }}'
  writeConnectionSecretToRef:
    name: '{{ .Values.adventurelog.database.userSecret }}'
