grocy:
  #
  # IMPORTANT NOTE
  #
  # This chart inherits from our common library chart. You can check the default values/options here:
  # https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
  #

  image:
    # -- image repository
    repository: linuxserver/grocy
    # -- image pull policy
    pullPolicy: IfNotPresent

  # -- environment variables. See more environment variables in the [grocy documentation](https://github.com/linuxserver/docker-grocy#parameters).
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: UTC
    # -- Set the container user id
    PUID: '1000'
    # -- Set the container group id
    PGID: '1000'

    GROCY_AUTH_CLASS: 'Grocy\Middleware\ReverseProxyAuthMiddleware'
    GROCY_REVERSE_PROXY_AUTH_HEADER: 'X-Pomerium-Claim-preferred_username'

  # -- Configures service settings for the chart.
  # @default -- See values.yaml
  service:
    main:
      ports:
        http:
          port: 80



  ingress:
    # -- Enable and configure ingress settings for the chart under this key.
    # @default -- See values.yaml
    main:
      enabled: true

      ingressClassName: pomerium

      labels:
        wan-mode: 'public'
        lan-mode: 'private'

      annotations:
        cert-manager.io/cluster-issuer: kjdev-cluster
        external-dns.alpha.kubernetes.io/target: k0s-dc1.resolvemy.host.
        ingress.pomerium.io/allowed_idp_claims: '{"groups": ["Network", "Server"]}'
        ingress.pomerium.io/preserve_host_header: 'true'
        ingress.pomerium.io/pass_identity_headers: 'true'
        ingress.pomerium.io/allow_websockets: 'true'

      hosts:
        -  # -- Host address. Helm template can be passed.
          host: grocy.controlcenter.house
          ## Configure the paths for the host
          paths:
            -  # -- Path.  Helm template can be passed.
              path: /
              # -- Ignored if not kubeVersion >= 1.14-0
              pathType: Prefix

      # -- Configure TLS for the ingress. Both secretName and hosts can process a Helm template.
      tls:
        - secretName: controlcenterhouse-default-certificates
          hosts:
            - '*.controlcenter.house'

  # -- Configure persistence settings for the chart under this key.
  # @default -- See values.yaml
  persistence:
    config:
      enabled: false

    # Let the viewcache only persist for the lifetime of the pod, otherwise
    # there will cases of blank pages when upgrading the image that require
    # manually clearing the directory
    viewcache:
      enabled: true
      type: emptyDir
      mountPath: /config/data/viewcache
