grocy:
  image:
    pullPolicy: IfNotPresent

  securityContext:
    readOnlyRootFilesystem: false
    runAsNonRoot: false

  podSecurityContext:
    runAsUser: 0
    runAsGroup: 0

  service:
    main:
      ports:
        main:
          port: 10013
          targetPort: 80

  persistence:
    config:
      enabled: false
      mountPath: "/config"

  portal:
    enabled: false



  # -- environment variables. See more environment variables in the [grocy documentation](https://github.com/linuxserver/docker-grocy#parameters).
  # @default -- See below
  env:
    # -- Set the container timezone
    TZ: UTC
    # -- Set the container user id
    PUID: '1000'
    # -- Set the container group id
    PGID: '1000'

    GROCY_AUTH_CLASS: 'Grocy\Middleware\ReverseProxyAuthMiddleware'
    GROCY_REVERSE_PROXY_AUTH_HEADER: 'X-Authentik-username'
    GROCY_DISABLE_AUTH: 'true'

