
rsshub:
  image:
    repository: tccr.io/truecharts/rsshub
    pullPolicy: IfNotPresent

  browserlessImage:
    repository: tccr.io/truecharts/browserless-chrome

  envValueFrom:
    REDIS_URL:
      secretKeyRef:
        name: rsshub-redis
        key: REDIS_URL

  ingress:
    main:
      enabled: true
      ingressClassName: traefik-core
      labels:
        wan-mode: 'public'
        lan-mode: 'private'
      annotations:
        cert-manager.io/cluster-issuer: kjdev-cluster
        external-dns.alpha.kubernetes.io/target: k0s-dc1.resolvemy.host.
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: 'true'
        traefik.ingress.kubernetes.io/router.middlewares: core-prod-pomerium-auth@kubernetescrd
        ingress.pomerium.io/allowed_idp_claims: '{"groups": ["Media Admins"]}'
      hosts:
        - host: feeds.kjmedia.stream
          paths:
            - path: '/'
              pathType: Prefix
      tls:
        - hosts:
            - '*.kjmedia.stream'
          secretName: kjmediastream-default-certificates
      
  secret:
    HTTP_BASIC_AUTH_NAME: ""
    HTTP_BASIC_AUTH_PASS: ""
    BITBUCKET_USERNAME: ""
    BITBUCKET_PASSWORD: ""
    GITHUB_ACCESS_TOKEN: ""
    GOOGLE_FONTS_API_KEY: ""
    YOUTUBE_KEY: ""
    TELEGRAM_TOKEN: ""
    LASTFM_API_KEY: ""

  env:
    PORT: "{{ .Values.service.main.ports.main.port }}"
    NODE_ENV: production

    CACHE_TYPE: "redis"
    PUPPETEER_WS_ENDPOINT: "ws://localhost:3000"
    NODE_NAME: "{{ .Release.Name }}-{{ randAlphaNum 5 }}"
    # User  defined
    # ALLOW_ORIGIN: ""
    DISALLOW_ROBOT: false
    TITLE_LENGTH_LIMIT: 150

  service:
    main:
      ports:
        main:
          port: 10191

  # Enabled redis
  redis:
    enabled: false
    existingSecret: null

  additionalContainers:
    browserless:
      name: browserless
      image: "{{ .Values.browserlessImage.repository }}:{{ .Values.browserlessImage.tag }}"
      ports:
        - containerPort: 3000
          name: main
