
rsshub:
  image:
    repository: tccr.io/truecharts/rsshub
    pullPolicy: IfNotPresent

  browserlessImage:
    repository: tccr.io/truecharts/browserless-chrome

  envValueFrom: null
      
  secret:
    HTTP_BASIC_AUTH_NAME: ""
    HTTP_BASIC_AUTH_PASS: ""
    BITBUCKET_USERNAME: ""
    BITBUCKET_PASSWORD: ""
    GITHUB_ACCESS_TOKEN: ""
    GOOGLE_FONTS_API_KEY: ""
    YOUTUBE_KEY: ""
    TELEGRAM_TOKEN: ""
    LASTFM_API_KEY: ""

  env:
    PORT: "{{ .Values.service.main.ports.main.port }}"
    NODE_ENV: production
    REDIS_URL: 'redis://10.1.1.68:6379/70'
    CACHE_TYPE: "redis"
    PUPPETEER_WS_ENDPOINT: "ws://localhost:3000"
    NODE_NAME: "{{ .Release.Name }}-{{ randAlphaNum 5 }}"
    # User  defined
    # ALLOW_ORIGIN: ""
    DISALLOW_ROBOT: false
    TITLE_LENGTH_LIMIT: 150

  service:
    main:
      ports:
        main:
          port: 10191

  # Enabled redis
  redis:
    enabled: false
    existingSecret: null

  additionalContainers:
    browserless:
      name: browserless
      image: "{{ .Values.browserlessImage.repository }}:{{ .Values.browserlessImage.tag }}"
      ports:
        - containerPort: 3000
          name: main
