apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ .Release.Name }}-maddy

spec:
  name: 'Maddy Email'

  psql:
    enabled: true
    crossplane:
      crossplaneProvider: {{ .Values.site.psql.crossplaneProvider | quote }}
      terraformProvider: {{ .Values.site.psql.terraformProvider | quote }}

  s3:
    enabled: true
    createBuckets: true
    createServiceAccount: true
    buckets:
      - 'mail-main'
    crossplane:
      crossplaneProvider: {{ .Values.site.s3.crossplaneProvider | quote }}
      terraformProvider: {{ .Values.site.s3.terraformProvider | quote }}
    writeServiceAccountCredentialsSecretRef:
      name: {{ printf "%s-maddy-s3-user" .Release.Name | quote }}
      namespace: {{ .Release.Namespace | quote }}

  groups:
    - 'LDAPService'

  writeConnectionSecretToRef:
    name: {{ printf "%s-maddy-creds" .Release.Name | quote }}
