apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: business-mail-maddy-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: {{ .Release.Name }}-maddy-s3
  data:
    #
    # Database
    #
    - secretKey: AccessKey
      remoteRef:
        key: Mail/Maddy/S3
        property: AccessKey

    - secretKey: SecretKey
      remoteRef:
        key: Mail/Maddy/S3
        property: SecretKey

