apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ .Release.Name }}-maddy

spec:
  name: Maddy Email

  buckets:
    - mail-main

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ .Release.Name }}-maddy-creds