apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: blink-links-server
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: blink-links-server-secrets

  data:
    - secretKey: OpenIDClientID
      remoteRef:
        key: Blink
        property: OpenIDClientID

    - secretKey: OpenIDClientSecret
      remoteRef:
        key: Blink
        property: OpenIDClientSecret

    - secretKey: DBURI
      remoteRef:
        key: Blink
        property: DBURI