{{- if .Values.blink.enabled }}
{{- $fullName := include "sharing.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ $fullName }}

    app.kubernetes.io/name: blink
    app.kubernetes.io/component: server

    {{- with .Values.blink.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with .Values.blink.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  
  name: {{ $fullName }}-blink

spec:
  replicas: {{ .Values.blink.replicaCount }}

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $fullName }}

      app.kubernetes.io/name: blink
      app.kubernetes.io/component: server

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $fullName }}

        app.kubernetes.io/name: blink
        app.kubernetes.io/component: server

        {{- with .Values.blink.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.blink.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:
      {{- with .Values.blink.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.blink.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}

      containers:
        - name: signal

          {{- with .Values.blink.image }}
          image: '{{ .repository }}{{ if .digest }}@{{ .digest }}{{ else }}:{{ .tag }}{{ end }}'
          imagePullPolicy: {{ .pullPolicy }}
          {{- end }}

          resources:
            {{- toYaml .Values.blink.resources | nindent 12 }}

          env:
            - name: NETBIRD_MGMT_API_ENDPOINT
              value: 0.0.0.0:67

            - name: NETBIRD_MGMT_GRPC_API_ENDPOINT
              value: ''



          ports:
            - containerPort: 80
              name: http

        {{- with .Values.blink.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      securityContext:
        seccompProfile:
          type: RuntimeDefault
      
      volumes:
        - configMap:
            name: "{{ $fullName }}-apiserver-config"
          name: apiserver-config
    
        {{- with .Values.blink.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

{{- end }}
