apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: blink-links-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: blink-links-server-secrets
    template:
      engineVersion: v2
      data:
        # multiline string
        DBURI: '{{`postgresql://{{ .Username }}:{{ .Password }}@{{ .Hostname }}:{{ .Port }}/{{ .Database }}`}}'


  data:
    - secretKey: OpenIDClientID
      remoteRef:
        key: Sharing/OIDC
        property: ClientID

    - secretKey: OpenIDClientSecret
      remoteRef:
        key: Sharing/OIDC
        property: ClientSecret

    - secretKey: Hostname
      remoteRef:
        key: Sharing/Database
        property: Hostname

    - secretKey: Port
      remoteRef:
        key: Sharing/Database
        property: Port

    - secretKey: Database
      remoteRef:
        key: Sharing/Database
        property: Database

    - secretKey: Username
      remoteRef:
        key: Sharing/Database
        property: Username

    - secretKey: Password
      remoteRef:
        key: Sharing/Database
        property: Password

    - secretKey: SessionSecret
      remoteRef:
        key: Sharing/Session
        property: SecretKey
