{{- if and .Values.blink.enabled .Values.blink.service.enabled }}
{{- $fullName := include "sharing.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: {{ $fullName }}

    app.kubernetes.io/name: blink
    app.kubernetes.io/component: server

    {{- with .Values.blink.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  name: {{ $fullName }}-blink-server

spec:
  type: {{ .Values.blink.service.type }}
  {{- with .Values.blink.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}

  ports:
    - name: http
      port: 80
      targetPort: http

  selector:
    app.kubernetes.io/instance: {{ $fullName }}

    app.kubernetes.io/name: blink
    app.kubernetes.io/component: server

{{- end }}
