apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-sharing-xbackbone-config-tpl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: mainvault-core

  target:
    name: business-sharing-xbackbone-config
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: business-sharing-xbackbone-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: config.php
  data:
    #
    # General AAA
    #
    - secretKey: Username
      remoteRef:
        key: Sharing/XBackbone/LDAP
        property: Username

    - secretKey: Password
      remoteRef:
        key: Sharing/XBackbone/LDAP
        property: Password

    #
    # S3
    #
    - secretKey: S3Bucket
      remoteRef:
        key: Sharing/XBackbone/S3
        property: Bucket

    - secretKey: S3SecretKey
      remoteRef:
        key: Sharing/XBackbone/S3
        property: SecretKey
