apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: business-sharing-xbackbone-config-tpl
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: business-sharing-xbackbone-config
    template:
      engineVersion: v2
      data:
        test: 'hi'
      templateFrom:
        - configMap:
            name: business-sharing-xbackbone-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: config.php
  data:
    #
    # General AAA
    #
    - secretKey: Username
      remoteRef:
        key: XBackbone
        property: Username

    - secretKey: Password
      remoteRef:
        key: XBackbone
        property: Password

    #
    # S3
    #
    - secretKey: S3Bucket
      remoteRef:
        key: XBackbone
        property: S3Bucket

    - secretKey: S3SecretKey
      remoteRef:
        key: XBackbone
        property: S3SecretKey
