apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: 'fitness-auth'
spec:
  targetRefs:
    - group: 'gateway.networking.k8s.io'
      kind: 'HTTPRoute'
      name: 'fitness'
  extAuth:
    failOpen: false
    headersToExtAuth:
      - 'cookie'
    http:
      headersToBackend:
        - 'set-cookie'
        - 'x-authentik-*'
        - 'authorization'
        - 'Content-Type'
        - 'Location'
      backendSettings:
        loadBalancer:
          type: 'ConsistentHash'
          consistentHash:
            type: 'SourceIP'
      backendRefs:
        - group: ''
          kind: 'Service'
          namespace: 'core-prod'
          name: 'aaa-myloginspace-proxy'
          port: 80
      path: '/outpost.goauthentik.io/auth/envoy'
---
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: '{{ .Release.Name }}-authentik'
spec:
  providerConfigRef:
    name: 'authentik'
  forProvider:
    source: 'Inline'
    module: | # hcl
      data "authentik_flow" "authorization" {
        slug = "default-provider-authorization-implicit-consent"
      }

      data "authentik_flow" "invalidation" {
        slug = "default-provider-invalidation-flow"
      }

      resource "authentik_provider_proxy" "app" {
        name               = "{{ .Release.Name }}"
        mode               = "forward_single"
        external_host      = "https://{{ required "opengym.hostname is required" .Values.opengym.hostname }}"
        authorization_flow = data.authentik_flow.authorization.id
        invalidation_flow  = data.authentik_flow.invalidation.id
      }

      resource "authentik_application" "app" {
        name              = "{{ required "authentik.application.displayName is required" .Values.authentik.application.displayName }}"
        slug              = "{{ .Release.Name }}"
        group             = "{{ required "authentik.application.group is required" .Values.authentik.application.group }}"
        protocol_provider = authentik_provider_proxy.app.id
      }
