{{- if and .Values.kamailio.enabled .Values.kamailio.publicExposure.enabled .Values.kamailio.publicExposure.sip.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: {{ $fullName }}-kamailio
  annotations:
    external-dns.kubernetes.io/hostname: '{{ .Values.kamailio.advertisedHost }}'

  labels:
    wan-mode: public
    lan-mode: private
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $.Values.gateway.name }}
      namespace: {{ $.Values.gateway.namespace }}
      sectionName: tls-sip

  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $fullName }}-kamailio
          port: 5061
          weight: 1
{{- end }}
