{{- if and .Values.kamailio.enabled .Values.kamailio.publicExposure.enabled .Values.kamailio.publicExposure.sip.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
{{ if .Values.kamailio.publicExposure.sip.tlsPassthrough }}
apiVersion: gateway.networking.k8s.io/v1
kind: TLSRoute
{{ else }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
{{ end }}
metadata:
  name: {{ $fullName }}-kamailio
  annotations:
    external-dns.kubernetes.io/hostname: '{{ .Values.sip.globalHost }},{{ include "avoip.sip.siteHost" . }}'
    # TODO: Remove the legacy ExternalDNS annotation after all controllers use v0.22.0+.
    external-dns.alpha.kubernetes.io/hostname: '{{ .Values.sip.globalHost }},{{ include "avoip.sip.siteHost" . }}'

  labels:
    wan-mode: public
    lan-mode: private
spec:
  {{ if .Values.kamailio.publicExposure.sip.tlsPassthrough }}
  hostnames:
    - '{{ include "avoip.sip.siteHost" . }}'
  {{ end }}
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $.Values.gateway.name }}
      namespace: {{ $.Values.gateway.namespace }}
      sectionName: sips-tls

  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $fullName }}-kamailio
          port: 5061
          weight: 1
{{- end }}
