{{- if and .Values.kamailio.enabled .Values.kamailio.publicExposure.enabled .Values.kamailio.publicExposure.sip.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: {{ $fullName }}-kamailio-udp

  labels:
    wan-mode: public
    lan-mode: private
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ $.Values.gateway.namespace }}
      name: {{ $.Values.gateway.name }}
      sectionName: sip-udp

  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: {{ $fullName }}-kamailio
          port: 5060
          weight: 1
{{- end }}
