{{- if and .Values.secrets.enabled .Values.mcp.search.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-brave-search
spec:
  {{- with .Values.secrets.secretStoreRef }}
  secretStoreRef:
    {{ toYaml . | nindent 4  }}
  {{- end }}

  target:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" $ }}-brave-search

  data:
    - secretKey: APIKey
      remoteRef:
        key: MCP/Search/Brave
        property: APIKey
{{- end }}