{{- if .Values.mas.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-runtime" .Values.mas.secretManagement.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.mas.secretManagement.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.mas.secretManagement.secretName | quote }}
    creationPolicy: 'Orphan'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'MATRIX_SECRET'
      remoteRef:
        key: {{ .Values.mas.secretManagement.remoteKey | quote }}
        property: {{ .Values.mas.secretManagement.matrixSecretKey | quote }}
    - secretKey: 'ENCRYPTION_KEY'
      remoteRef:
        key: {{ .Values.mas.secretManagement.remoteKey | quote }}
        property: {{ .Values.mas.secretManagement.encryptionKey | quote }}
    - secretKey: 'RSA_KEY'
      remoteRef:
        key: {{ .Values.mas.secretManagement.remoteKey | quote }}
        property: {{ .Values.mas.secretManagement.signingKey | quote }}
{{- end }}
