apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Values.synapse.secretManagement.generatorName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  length: 64
  digits: 0
  symbols: 0
  allowRepeat: true
  secretKeys:
    - 'MACAROON_SECRET_KEY'
    - 'FORM_SECRET'
  encoding: 'hex'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-generate" .Values.synapse.secretManagement.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '-9'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: {{ .Values.synapse.secretManagement.bootstrapSecretName | quote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: 'Password'
          name: {{ .Values.synapse.secretManagement.generatorName | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-pull" .Values.synapse.secretManagement.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.synapse.secretManagement.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.synapse.secretManagement.secretName | quote }}
    creationPolicy: 'Orphan'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'MACAROON_SECRET_KEY'
      remoteRef:
        key: {{ .Values.synapse.secretManagement.remoteKey | quote }}
        property: 'MACAROON_SECRET_KEY'
    - secretKey: 'FORM_SECRET'
      remoteRef:
        key: {{ .Values.synapse.secretManagement.remoteKey | quote }}
        property: 'FORM_SECRET'
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-push" .Values.synapse.secretManagement.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  updatePolicy: 'Replace'
  deletionPolicy: 'None'
  secretStoreRefs:
    - {{- toYaml .Values.synapse.secretManagement.secretStoreRef | nindent 6 }}
  selector:
    secret:
      name: {{ .Values.synapse.secretManagement.bootstrapSecretName | quote }}
  data:
    - match:
        secretKey: 'MACAROON_SECRET_KEY'
        remoteRef:
          remoteKey: {{ .Values.synapse.secretManagement.remoteKey | quote }}
          property: 'MACAROON_SECRET_KEY'
    - match:
        secretKey: 'FORM_SECRET'
        remoteRef:
          remoteKey: {{ .Values.synapse.secretManagement.remoteKey | quote }}
          property: 'FORM_SECRET'
