{{- if .Values.turn.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.turn.secret.name | quote }}
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.turn.secret.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.turn.secret.name | quote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'TURN_SHARED_SECRET'
      remoteRef:
        key: {{ .Values.turn.secret.remoteKey | quote }}
        property: {{ .Values.turn.secret.remoteProperty | quote }}
{{- end }}
