apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: {{ .Values.synapse.user.name | quote }}
  annotations:
    argocd.argoproj.io/sync-options: 'Prune=false,Delete=false'
spec:
  name: 'Matrix Synapse'
  username: {{ .Values.synapse.user.username | quote }}
  serviceAccount: true
  psql:
    enabled: true
    createUserDatabase: true
    databases:
      - {{ .Values.synapse.psql.database | quote }}
    crossplane:
      crossplaneProvider: {{ .Values.synapse.psql.crossplaneProvider | quote }}
      terraformProvider: {{ .Values.synapse.psql.terraformProvider | quote }}
  groups:
    - 'LDAPService'
  writeConnectionSecretToRef:
    name: {{ .Values.synapse.user.connectionSecretName | quote }}
