{{- range $desktop := .Values.desktops }}
{{- if $desktop.enabled }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $.Release.Name }}-desktop-{{ $desktop.name }}
  labels:
    wan-mode: 'public'
    lan-mode: 'private'
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $.Values.gateway.name | quote }}
      namespace: {{ $.Values.gateway.namespace | quote }}
      sectionName: {{ $.Values.gateway.sectionName | quote }}
  hostnames:
    - {{ required (printf "desktops[%s].hostname is required" $desktop.name) $desktop.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ''
          kind: Service
          name: {{ $.Release.Name }}-desktop-{{ $desktop.name }}
          port: 80
          weight: 1
{{- end }}
{{- end }}

