apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawio
spec:
  replicas: 1

  revisionHistoryLimit: 3

  selector:
    matchLabels:
      app: drawio-ui

  template:
    metadata:
      labels:
        app: drawio-ui

    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 1000
        fsGroup: 1000

      containers:
        - image: jgraph/drawio:latest
          name: drawio-ui
          resources:
            requests:
              cpu: 15m
              memory: 1313M
            limits:
              cpu: 15m
              memory: 1313M

          securityContext:
            readOnlyRootFilesystem: true

          ports:
            - name: http
              containerPort: 8080
