apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: drawio-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - name: ingress-gw
  hostnames:
    - 'draw.mylogin.space'
  rules:
    - backendRefs:
        - name: drawio-ui
          port: 80