apiVersion: v1
kind: Service
metadata:
  name: drawio-ui
spec:
  clusterIP: None
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      appProtocol: http
      name: http
  selector:
    app: drawio-ui
