{{- $_ := required "authentik.providerConfigRef is required" .Values.authentik.providerConfigRef -}}
{{- $_ := required "authentik.application.displayName is required" .Values.authentik.application.displayName -}}
{{- $_ := required "authentik.application.group is required" .Values.authentik.application.group -}}
{{- $_ := required "authentik.outpost.name is required" .Values.authentik.outpost.name -}}
{{- $_ := required "authentik.outpost.namespace is required" .Values.authentik.outpost.namespace -}}
{{- $_ := required "authentik.outpost.port is required" .Values.authentik.outpost.port -}}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-auth'
spec:
  targetRefs:
    - group: 'gateway.networking.k8s.io'
      kind: 'HTTPRoute'
      name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-app'
  extAuth:
    failOpen: false
    headersToExtAuth:
      - 'cookie'
      - 'x-forwarded-host'
      - 'x-forwarded-method'
      - 'x-forwarded-proto'
      - 'x-forwarded-uri'
    http:
      headersToBackend:
        - 'set-cookie'
        - 'x-authentik-username'
        - 'x-authentik-groups'
        - 'x-authentik-entitlements'
        - 'x-authentik-email'
        - 'x-authentik-name'
        - 'x-authentik-uid'
        - 'x-authentik-jwt'
        - 'x-authentik-meta-jwks'
        - 'x-authentik-meta-outpost'
        - 'x-authentik-meta-provider'
        - 'x-authentik-meta-app'
        - 'x-authentik-meta-version'
        - 'authorization'
        - 'Content-Type'
        - 'Location'
      backendSettings:
        loadBalancer:
          type: 'ConsistentHash'
          consistentHash:
            type: 'SourceIP'
      backendRefs:
        - group: ''
          kind: 'Service'
          namespace: '{{ .Values.authentik.outpost.namespace }}'
          name: '{{ .Values.authentik.outpost.name }}'
          port: {{ .Values.authentik.outpost.port }}
      path: '/outpost.goauthentik.io/auth/envoy'
{{- if .Values.httpbin.enabled }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-httpbin-auth'
spec:
  targetRefs:
    - group: 'gateway.networking.k8s.io'
      kind: 'HTTPRoute'
      name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-httpbin'
  extAuth:
    failOpen: false
    headersToExtAuth:
      - 'cookie'
      - 'x-forwarded-host'
      - 'x-forwarded-method'
      - 'x-forwarded-proto'
      - 'x-forwarded-uri'
    http:
      headersToBackend:
        - 'set-cookie'
        - 'x-authentik-username'
        - 'x-authentik-groups'
        - 'x-authentik-entitlements'
        - 'x-authentik-email'
        - 'x-authentik-name'
        - 'x-authentik-uid'
        - 'x-authentik-jwt'
        - 'x-authentik-meta-jwks'
        - 'x-authentik-meta-outpost'
        - 'x-authentik-meta-provider'
        - 'x-authentik-meta-app'
        - 'x-authentik-meta-version'
        - 'authorization'
        - 'Content-Type'
        - 'Location'
      backendSettings:
        loadBalancer:
          type: 'ConsistentHash'
          consistentHash:
            type: 'SourceIP'
      backendRefs:
        - group: ''
          kind: 'Service'
          namespace: '{{ .Values.authentik.outpost.namespace }}'
          name: '{{ .Values.authentik.outpost.name }}'
          port: {{ .Values.authentik.outpost.port }}
      path: '/outpost.goauthentik.io/auth/envoy'
{{- end }}
{{- if .Values.wygiwyh.enabled }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-wygiwyh-auth'
spec:
  targetRefs:
    - group: 'gateway.networking.k8s.io'
      kind: 'HTTPRoute'
      name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-wygiwyh'
  extAuth:
    failOpen: false
    headersToExtAuth:
      - 'cookie'
      - 'x-forwarded-host'
      - 'x-forwarded-method'
      - 'x-forwarded-proto'
      - 'x-forwarded-uri'
    http:
      headersToBackend:
        - 'set-cookie'
        - 'x-authentik-email'
        - 'x-authentik-username'
        - 'Content-Type'
        - 'Location'
      backendRefs:
        - group: ''
          kind: 'Service'
          namespace: '{{ .Values.authentik.outpost.namespace }}'
          name: '{{ .Values.authentik.outpost.name }}'
          port: {{ .Values.authentik.outpost.port }}
      path: '/outpost.goauthentik.io/auth/envoy'
{{- end }}
{{- if .Values.financialDashboard.enabled }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-financial-dashboard-auth'
spec:
  targetRefs:
    - group: 'gateway.networking.k8s.io'
      kind: 'HTTPRoute'
      name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-financial-dashboard'
  extAuth:
    failOpen: false
    headersToExtAuth:
      - 'cookie'
      - 'x-forwarded-host'
      - 'x-forwarded-method'
      - 'x-forwarded-proto'
      - 'x-forwarded-uri'
    http:
      headersToBackend:
        - 'set-cookie'
        - 'Content-Type'
        - 'Location'
      backendRefs:
        - group: ''
          kind: 'Service'
          namespace: '{{ .Values.authentik.outpost.namespace }}'
          name: '{{ .Values.authentik.outpost.name }}'
          port: {{ .Values.authentik.outpost.port }}
      path: '/outpost.goauthentik.io/auth/envoy'
{{- end }}
---
apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-authentik'
spec:
  providerConfigRef:
    name: '{{ .Values.authentik.providerConfigRef }}'
  forProvider:
    source: 'Inline'
    module: | # hcl
      data "authentik_flow" "authorization" {
        slug = "default-provider-authorization-implicit-consent"
      }

      data "authentik_flow" "invalidation" {
        slug = "default-provider-invalidation-flow"
      }

      resource "authentik_provider_proxy" "app" {
        name               = "{{ include "bjw-s.common.lib.chart.names.fullname" . }}"
        mode               = "forward_single"
        external_host      = "https://{{ required "firefly.hostname is required" .Values.firefly.hostname }}"
        authorization_flow = data.authentik_flow.authorization.id
        invalidation_flow  = data.authentik_flow.invalidation.id
      }

      resource "authentik_application" "app" {
        name              = "{{ required "authentik.application.displayName is required" .Values.authentik.application.displayName }}"
        slug              = "{{ include "bjw-s.common.lib.chart.names.fullname" . }}"
        group             = "{{ required "authentik.application.group is required" .Values.authentik.application.group }}"
        protocol_provider = authentik_provider_proxy.app.id
      }

      {{- if .Values.wygiwyh.enabled }}
      resource "authentik_provider_proxy" "wygiwyh" {
        name               = "{{ include "bjw-s.common.lib.chart.names.fullname" . }}-wygiwyh"
        mode               = "forward_single"
        external_host      = "https://{{ .Values.wygiwyh.hostname }}"
        authorization_flow = data.authentik_flow.authorization.id
        invalidation_flow  = data.authentik_flow.invalidation.id
      }

      resource "authentik_application" "wygiwyh" {
        name              = "WYGIWYH"
        slug              = "{{ include "bjw-s.common.lib.chart.names.fullname" . }}-wygiwyh"
        group             = "Personal"
        protocol_provider = authentik_provider_proxy.wygiwyh.id
      }
      {{- end }}

      {{- if .Values.financialDashboard.enabled }}
      resource "authentik_provider_proxy" "financial_dashboard" {
        name               = "{{ include "bjw-s.common.lib.chart.names.fullname" . }}-financial-dashboard"
        mode               = "forward_single"
        external_host      = "https://{{ .Values.financialDashboard.hostname }}"
        authorization_flow = data.authentik_flow.authorization.id
        invalidation_flow  = data.authentik_flow.invalidation.id
      }

      resource "authentik_application" "financial_dashboard" {
        name              = "Financial Dashboard"
        slug              = "{{ include "bjw-s.common.lib.chart.names.fullname" . }}-financial-dashboard"
        group             = "Personal"
        protocol_provider = authentik_provider_proxy.financial_dashboard.id
      }
      {{- end }}

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-authentik-outpost'
spec:
  parentRefs:
    - kind: 'Gateway'
      name: '{{ .Values.gateway.name }}'
      namespace: '{{ .Values.gateway.namespace }}'
      sectionName: '{{ .Values.gateway.sectionName }}'
  hostnames:
    - '{{ .Values.firefly.hostname }}'
    {{- if .Values.wygiwyh.enabled }}
    - '{{ .Values.wygiwyh.hostname }}'
    {{- end }}
    {{- if .Values.financialDashboard.enabled }}
    - '{{ .Values.financialDashboard.hostname }}'
    {{- end }}
  rules:
    - matches:
        - path:
            type: 'PathPrefix'
            value: '/outpost.goauthentik.io'
      backendRefs:
        - group: ''
          kind: 'Service'
          name: '{{ .Values.authentik.outpost.name }}'
          namespace: '{{ .Values.authentik.outpost.namespace }}'
          port: {{ .Values.authentik.outpost.port }}
