{{- if ne .Release.Namespace .Values.authentik.outpost.namespace }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-authentik-outpost'
  namespace: '{{ .Values.authentik.outpost.namespace }}'
spec:
  from:
    - group: 'gateway.networking.k8s.io'
      kind: 'HTTPRoute'
      namespace: '{{ .Release.Namespace }}'
    - group: 'gateway.envoyproxy.io'
      kind: 'SecurityPolicy'
      namespace: '{{ .Release.Namespace }}'
  to:
    - group: ''
      kind: 'Service'
      name: '{{ .Values.authentik.outpost.name }}'
{{- end }}
