{{- if .Values.wygiwyh.enabled }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-wygiwyh-secret-key'
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  length: 50
  digits: 10
  symbols: 10
  allowRepeat: true
  secretKeys:
    - 'SECRET_KEY'
  encoding: 'raw'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-wygiwyh-secret-key'
  annotations:
    argocd.argoproj.io/sync-wave: '-9'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: '{{ .Values.wygiwyh.secretKeySecret }}'
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: 'Password'
          name: '{{ include "bjw-s.common.lib.chart.names.fullname" . }}-wygiwyh-secret-key'
{{- end }}
