URL: 'https://mail.mylogin.space'

clusterDNS: 'k0s.resolvemy.host'

email:
  domain: mail.mylogin.space
  support: k@mylogin.space
  tls:
    secretName: myloginspace-default-certificates

  postfix:
    server: 10.1.1.25

simplelogin:
  enabled: false

dkim-manager:
  image:

    # image.pullPolicy -- dkim-manager image pullPolicy.
    pullPolicy: Always

  controller:
    # controller.replicas -- Specify the number of replicas of the controller Pod.
    replicas: 2

    # controller.resources -- Specify resources.
    resources:
      requests:
        cpu: 100m
        memory: 20Mi

    # controller.terminationGracePeriodSeconds -- Specify terminationGracePeriodSeconds.
    terminationGracePeriodSeconds: 10

    # controller.extraArgs -- Optional additional arguments.
    extraArgs:
      - --leader-elect

  namespaced: true
  namespace: ""

  external-dns:
    enabled: false
    serviceAccount:
      create: false
    rbac:
      create: false
    env: []
    sources:
      - crd
    logFormat: json
    txtPrefix: dkim-manager
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --managed-record-types=TXT
