apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: business-hpscholing-hpcode
  namespace: argocd
spec:
  destination:
    server: https://172.20.52.1:6443
    namespace: core-prod

  project: core

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  source:
    repoURL: https://gitlab.git.writemy.codes/KJDev/core-business2.git
    path: HPSchool/PHP
    targetRevision: HEAD
