apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pdf-ingress

  labels:
    wan-mode: 'public'
    lan-mode: 'private'

spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      namespace: {{ .Values.gateway.namespace }}
      name: {{ .Values.gateway.name }}
      sectionName: {{ .Values.gateway.sectionName }}

  hostnames:
    - 'pdf.mylogin.space'
  rules:
    - backendRefs:
        - group: ''
          kind: Service
          name: pdf-edit-ui
          port: 80
          weight: 1