{{- $fullName := include "knowledge.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-contextualise

  labels:
    app: {{ $fullName }}-contextualise

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ $fullName }}-contextualise

  template:
    metadata:
      labels:
        app: {{ $fullName }}-contextualise

    spec:
      containers:
        - image: kristianfoss/contextualise:core
          name: contextualise

          ports:
            - name: http
              containerPort: 5000

          env:
            - name: CONTEXTUALISE_SETTINGS
              value: /src/contextualise/settings.cfg

          volumeMounts:
            - mountPath: /src/contextualise/settings.cfg
              name: contextualise-config
              subPath: settings.cfg

            - mountPath: /data
              name: data-volume

      volumes:
        - name: contextualise-config
          configMap:
            name: {{ $fullName }}-contextualise

        - name: data-volume
          emptyDir: {}