apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-config

data:
  dovecot.conf: |
    # MUST be the first setting in Dovecot 2.4 config.
    dovecot_config_version = 2.4.0
    dovecot_storage_version = 2.4.0

    !include /etc/dovecot/vendor.d/rootless.conf

    protocols = imap pop3 lmtp
    submission_host = mail.mylogin.space:25
    log_path = /dev/stderr
    info_log_path = /dev/stdout
    debug_log_path = /dev/stdout

    auth_allow_cleartext = yes

    #
    # Users
    #
    lmtp_save_to_detail_mailbox = yes
    recipient_delimiter = +


    ###############
    # Authentication
    ###############
    auth_mechanisms {
      plain = yes
      login = yes
    }

    !include /etc/dovecot/dovecot-ldap.conf

    ssl = yes
    ssl_server_cert_file = /etc/tls/mail/tls.crt
    ssl_server_key_file = /etc/tls/mail/tls.key

    service auth {
      inet_listener auth {
        port = 12345
      }
    }

    service lmtp {
      inet_listener lmtp {
        port = 2525
      }
    }


    #
    # IMAP
    #
    mail_driver = imapc

    imapc_host = int-imap.mylogin.space
    imapc_ssl = imaps
    imapc_port = 993

    imapc_user = %{userdb:uuid}@mylogin.space
    imapc_password = masteruser-secret

    imapc_sasl_mechanisms {
      login = yes
    }

    imapc_features {
      no-modseq = yes
      no-fetch-bodystructure = yes
    }


    service imap {
      imap_capability {	
        CONDSTORE = no	
        QRESYNC = no	
      }
    }

    !include /etc/dovecot/namespaces/*.conf
