apiVersion: v1
kind: ConfigMap
metadata:
  name: business-mail-dovecot-auth-config-tpl

data:
  dovecot-ldap.conf.ext: |
    {{`
    ldap_uris = ldaps://ldap.mylogin.space
    ldap_auth_dn = cn={{ .Username }},ou=users,dc=ldap,dc=mylogin,dc=space
    ldap_auth_dn_password = {{ .Password }}
    ldap_base = dc=ldap,dc=mylogin,dc=space
    
    passdb ldap {
      # 2.3: auth_bind = yes
      bind = yes

      bind_userdn = cn=%{user},ou=users,dc=ldap,dc=mylogin,dc=space
    }

    userdb ldap {
      ldap_connection_group = userdb

      filter = (&(objectClass=user)(|(cn=%{user | username})(mail=%{user})))

      fields {
        # You need this because your imapc_user uses %{userdb:uuid}@mylogin.space
        uuid = %{ldap:uid}
        uid = %{ldap:uidNumber}
        gid = %{ldap:gidNumber}
      }

      iterate_filter = (objectClass=user)

      iterate_fields {
        user = %{ldap:mail}
      }
    }
    `}}