{{- if and .Values.homer.enabled (eq .Values.cluster.type "hub") .Values.kamailio.enabled }}
{{- $fullName := include "avoip.fullname" . -}}
{{- $terraformProvider := default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.homer.database.terraformProvider -}}
{{- $crossplaneProvider := default (printf "psql-%s-%s" .Values.datacenter .Values.region) .Values.homer.database.crossplaneProvider -}}
---
apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: '{{ $fullName }}-homer'
spec:
  name: 'AVoIP Homer'
  username: '{{ .Values.homer.database.username }}'
  serviceAccount: true
  groups:
    - 'LDAPService'
  psql:
    enabled: true
    createUserDatabase: false
    databases:
      - '{{ .Values.homer.database.dataDatabase }}'
      - '{{ .Values.homer.database.configDatabase }}'
    crossplane:
      terraformProvider: '{{ $terraformProvider }}'
      crossplaneProvider: '{{ $crossplaneProvider }}'
  writeConnectionSecretToRef:
    name: '{{ default (printf "%s-homer" $fullName) .Values.homer.database.userSecret }}'
{{- end }}
