{{- if .Values.landingHttpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.forecastle.nameOverride | default "landing" | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    wan-mode: 'public'
spec:
  parentRefs:
{{ toYaml .Values.forecastle.forecastle.httpRoute.parentRefs | nindent 4 }}
  hostnames:
{{ toYaml .Values.forecastle.forecastle.httpRoute.hostnames | nindent 4 }}
  rules:
{{- range .Values.forecastle.forecastle.httpRoute.rules }}
    -
{{- with .matches }}
      matches:
{{ toYaml . | nindent 8 }}
{{- end }}
      backendRefs:
        - name: {{ $.Values.forecastle.nameOverride | default "landing" | quote }}
          port: {{ $.Values.landingHttpRoute.backendPort }}
          weight: 1
{{- end }}
{{- end }}
