apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpschool-phpcore
  namespace: core-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: infra1-storage
