{{- $remoteKey := default (printf "Social/Fediverse/%s/%s/%s/Mastodon" .Values.region .Values.datacenter .Values.cluster.name) .Values.secretManagement.remoteKey -}}
{{- $redisRemoteKey := default (printf "Storage/DragonFly/CoRE/%s/%s/%s/Creds" .Values.region .Values.datacenter .Values.cluster.name) .Values.redis.remoteRef.key -}}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Values.secretManagement.random.generatorName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '-10'
spec:
  length: 128
  digits: 16
  symbols: 0
  allowRepeat: true
  secretKeys:
    - 'SECRET_KEY_BASE'
    - 'OTP_SECRET'
  encoding: 'base64url'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-generate" .Values.secretManagement.random.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '-9'
spec:
  refreshPolicy: 'CreatedOnce'
  target:
    name: {{ .Values.secretManagement.random.bootstrapSecretName | quote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: 'Password'
          name: {{ .Values.secretManagement.random.generatorName | quote }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-pull" .Values.secretManagement.random.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.secretManagement.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.secretManagement.random.secretName | quote }}
    creationPolicy: 'Orphan'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'SECRET_KEY_BASE'
      remoteRef:
        key: {{ $remoteKey | quote }}
        property: 'SECRET_KEY_BASE'
    - secretKey: 'OTP_SECRET'
      remoteRef:
        key: {{ $remoteKey | quote }}
        property: 'OTP_SECRET'
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-generate-push" .Values.secretManagement.random.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  updatePolicy: 'Replace'
  deletionPolicy: 'None'
  secretStoreRefs:
    - {{- toYaml .Values.secretManagement.secretStoreRef | nindent 6 }}
  selector:
    secret:
      name: {{ .Values.secretManagement.random.bootstrapSecretName | quote }}
  data:
    - match:
        secretKey: 'SECRET_KEY_BASE'
        remoteRef:
          remoteKey: {{ $remoteKey | quote }}
          property: 'SECRET_KEY_BASE'
    - match:
        secretKey: 'OTP_SECRET'
        remoteRef:
          remoteKey: {{ $remoteKey | quote }}
          property: 'OTP_SECRET'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-pull" .Values.secretManagement.vapid.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.secretManagement.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.secretManagement.vapid.secretName | quote }}
    creationPolicy: 'Orphan'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'VAPID_PRIVATE_KEY'
      remoteRef:
        key: {{ $remoteKey | quote }}
        property: 'VAPID_PRIVATE_KEY'
    - secretKey: 'VAPID_PUBLIC_KEY'
      remoteRef:
        key: {{ $remoteKey | quote }}
        property: 'VAPID_PUBLIC_KEY'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ printf "%s-pull" .Values.secretManagement.encryption.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.secretManagement.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.secretManagement.encryption.secretName | quote }}
    creationPolicy: 'Orphan'
    deletionPolicy: 'Retain'
  data:
    - secretKey: 'ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY'
      remoteRef:
        key: {{ $remoteKey | quote }}
        property: 'ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY'
    - secretKey: 'ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT'
      remoteRef:
        key: {{ $remoteKey | quote }}
        property: 'ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT'
    - secretKey: 'ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY'
      remoteRef:
        key: {{ $remoteKey | quote }}
        property: 'ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY'
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-push" .Values.secretManagement.vapid.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  updatePolicy: 'Replace'
  deletionPolicy: 'None'
  secretStoreRefs:
    - {{- toYaml .Values.secretManagement.secretStoreRef | nindent 6 }}
  selector:
    secret:
      name: {{ .Values.secretManagement.vapid.bootstrapSecretName | quote }}
  data:
    - match:
        secretKey: 'VAPID_PRIVATE_KEY'
        remoteRef:
          remoteKey: {{ $remoteKey | quote }}
          property: 'VAPID_PRIVATE_KEY'
    - match:
        secretKey: 'VAPID_PUBLIC_KEY'
        remoteRef:
          remoteKey: {{ $remoteKey | quote }}
          property: 'VAPID_PUBLIC_KEY'
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-push" .Values.secretManagement.encryption.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  updatePolicy: 'Replace'
  deletionPolicy: 'None'
  secretStoreRefs:
    - {{- toYaml .Values.secretManagement.secretStoreRef | nindent 6 }}
  selector:
    secret:
      name: {{ .Values.secretManagement.vapid.bootstrapSecretName | quote }}
  data:
    - match:
        secretKey: 'ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY'
        remoteRef:
          remoteKey: {{ $remoteKey | quote }}
          property: 'ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY'
    - match:
        secretKey: 'ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT'
        remoteRef:
          remoteKey: {{ $remoteKey | quote }}
          property: 'ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT'
    - match:
        secretKey: 'ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY'
        remoteRef:
          remoteKey: {{ $remoteKey | quote }}
          property: 'ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY'
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redis.secretName | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  refreshInterval: '1h'
  secretStoreRef:
    {{- toYaml .Values.redis.secretStoreRef | nindent 4 }}
  target:
    name: {{ .Values.redis.secretName | quote }}
    creationPolicy: 'Owner'
    deletionPolicy: 'Retain'
  data:
    - secretKey: {{ .Values.redis.passwordSecretKey | quote }}
      remoteRef:
        key: {{ $redisRemoteKey | quote }}
        property: {{ .Values.redis.remoteRef.property | quote }}
