{{- if $.Values.speeches.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: {{ .Release.Name }}-speeches
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: {{ .Release.Name }}-speeches

  timeout:
    http:
      requestTimeout: 0s
      maxStreamDuration: 0s
      streamIdleTimeout: 0s

  loadBalancer:
    type: ConsistentHash
    consistentHash:
      type: Cookie
      cookie:
        name: 'core-speaches-session'
        ttl: '10800s'
        attributes:
          SameSite: 'Lax'
          Secure: 'true'

  healthCheck:
    active:
      interval: 5s
      timeout: 2s
      type: HTTP
      http:
        path: /health
        expectedStatuses:
          - 200
{{- end }}
