apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: business-office-extras
  namespace: argocd
spec:
  destination:
    server: https://10.1.1.40:443
    namespace: core-prod

  project: core

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  source:
    repoURL: https://gitlab.git.writemy.codes/KJDev/core-business.git
    path: Extras/Office
    targetRevision: HEAD
