apiVersion: v2
version: 1.0.0
name: core-business-office

dependencies:
  - name: common
    version: 4.2.0
    repository: https://bjw-s-labs.github.io/helm-charts/

  #
  # Collabora
  #
  - name: collabora-online
    version: 1.1.31
    repository: https://collaboraonline.github.io/online/
  
  #
  # NextCloud
  #
  - name: nextcloud
    version: '6.6.3'
    repository: https://nextcloud.github.io/helm/

  #
  # Vikunja
  #
  - name: vikunja
    version: 6.1.2
    condition: vikunja.enabled
    repository: https://k8s-at-home.com/charts/
