apiVersion: v2
version: 1.0.0
name: core-business-office

dependencies:
  #
  # Collabora
  #
  - name: collabora-code
    version: 2.5.0
    repository: https://chrisingenhaag.github.io/helm/
  
  #
  # NextCloud
  #
  - name: nextcloud
    version: 3.1.2
    repository: https://nextcloud.github.io/helm/

  #
  # Vikunja
  #
  - name: vikunja
    version: 6.1.2
    condition: vikunja.enabled
    repository: https://k8s-at-home.com/charts/
