apiVersion: v2
version: 1.0.0
name: core-business-office

dependencies:
  #
  # Collabora
  #
  - name: collabora-code
    version: 2.2.1
    repository: https://chrisingenhaag.github.io/helm/
  
  #
  # NextCloud
  #
  - name: nextcloud
    version: 2.14.2
    repository: https://nextcloud.github.io/helm/
