apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-business-office-collabora-helm
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: k0s-cntrl
            url: https://k0s-dc1-kubernetes-default.service.dc1.kjdev:6443
            ingress: collabora.mylogin.space
            environment: 'prod'
  template:
    metadata:
      name: '{{cluster}}-business-office-collabora-helm'
    spec:
      project: core
      # syncPolicy:
      #   automated:
      #     selfHeal: true
      #     prune: true
      source:
        repoURL: https://chrisingenhaag.github.io/helm/
        chart: collabora-code
        path: collabora-code
        targetRevision: 2.2.1
        helm:
          releaseName: collabora-code-{{ environment }}
          values: |
            # Default values for collabora-code.
            # This is a YAML-formatted file.
            # Declare variables to be passed into your templates.

            replicaCount: 1

            image:
              repository: collabora/code
              tag: 6.4.14.3
              pullPolicy: IfNotPresent

            strategy: Recreate

            nameOverride: ""
            fullnameOverride: ""

            service:
              type: ClusterIP
              port: 9980

            ingress:
              enabled: false
              annotations: {}
              paths: []
              hosts: []
              tls: []

            collabora:
              DONT_GEN_SSL_CERT: true
              domain: nextcloud\\.kristianjones\\.dev
              extra_params: --o:ssl.termination=true --o:ssl.enable=false
              server_name: collabora\.mylogin\.space
              password: examplepass
              username: admin
              dictionaries: de_DE en_GB en_US es_ES fr_FR it nl pt_BR pt_PT ru

            securitycontext:
              allowPrivilegeEscalation: true
              capabilities:
                add:
                - MKNOD

            resources: {}
              # limits:
              #  cpu: 100m
              #  memory: 128Mi
              # requests:
              #  cpu: 100m
              #  memory: 128Mi

            nodeSelector: {}

            tolerations: []

            affinity: {}

            livenessProbe:
              enabled: true
              initialDelaySeconds: 30
              timeoutSeconds: 2
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
              scheme: HTTP
              path: /

            readinessProbe:
              enabled: true
              initialDelaySeconds: 30
              timeoutSeconds: 2
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
              scheme: HTTP
              path: /

      destination:
        server: '{{url}}'
        namespace: core-prod
