apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: mail-postfix

spec:
  name: 'Postfix'

  psql:
    enabled: true
    createUserDatabase: false
    databases:
      - 'simplelogin'
    crossplane:
      crossplaneProvider: {{ .Values.site.psql.crossplaneProvider | quote }}
      terraformProvider: {{ .Values.site.psql.terraformProvider | quote }}

  groups:
    - 'LDAPService'

  writeConnectionSecretToRef:
    name: {{ printf "%s-postfix" .Release.Name | quote }}
