apiVersion: v1
kind: Service
metadata:
  name: postfix

  annotations:
    purelb.io/allow-shared-ip: mail.mylogin.space
    purelb.io/service-group: anycast
    purelb.io/allow-local: 'true'
    purelb.io/addresses: '66.165.222.125'

spec:
  allocateLoadBalancerNodePorts: false
  type: LoadBalancer

  ports:
    - name: smtp

      protocol: TCP
      appProtocol: smtp

      port: 25
      targetPort: smtp


    - name: submissions

      protocol: TCP
      appProtocol: submissions

      port: 465
      targetPort: smtp-tls


    - name: smtp-starttls

      protocol: TCP
      appProtocol: submission

      port: 587
      targetPort: smtp-starttls


    - name: smtp-auth

      protocol: TCP

      port: 10025
      targetPort: smtp-auth

  selector:
    app.kubernetes.io/name: simplelogin
    app.kubernetes.io/component: postfix

