apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: simplelogin-postfix-config
spec:
  secretStoreRef:
    {{- toYaml .Values.credentialsSync.secretStoreRef | nindent 4 }}
  
  target:
    name: simplelogin-postfix-config
    template:
      engineVersion: v2

      templateFrom:
        - configMap:
            name: simplelogin-postfix-config-tpl
            # here you define the keys that should be used as template
            items:
              - key: pgsql-relay-domains.cf
              - key: pgsql-transport-maps.cf
  data:
    #
    # Database
    #
    - secretKey: DatabaseDatabase
      remoteRef:
        key: {{ include "mail.credentialsRemoteKey" (dict "root" . "name" "Postfix/Database") | quote }}
        property: Database

    - secretKey: DatabasePassword
      remoteRef:
        key: {{ include "mail.credentialsRemoteKey" (dict "root" . "name" "Postfix/Database") | quote }}
        property: Password

    - secretKey: DatabaseUser
      remoteRef:
        key: {{ include "mail.credentialsRemoteKey" (dict "root" . "name" "Postfix/Database") | quote }}
        property: Username
