apiVersion: mylogin.space/v1alpha1
kind: User
metadata:
  name: mail-postfix

spec:
  name: Postfix

  database:
    name: simplelogin

  groups:
    - LDAPService

  writeConnectionSecretToRef:
    name: {{ .Release.Name }}-postfix