apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: core-backplane-business-communication-mattermost-secrets
  namespace: argocd
spec:
  destination:
    server: https://10.1.1.40:443
    namespace: core-prod

  project: core

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  source:
    repoURL: https://gitlab.git.writemy.codes/KJDev/core-business2.git
    path: Mattermost/Secrets
    targetRevision: HEAD
