apiVersion: v2

version: 1.0.0

name: core-business-comms

dependencies:
  #
  # Mattermost
  #
  - name: mattermost-team-edition
    repository: https://helm.mattermost.com
    condition: mattermost-team-edition.enabled
    version: 6.6.9
