apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: core-teams
  spec:
    template:
      metadata:
        annotations:
          sidecar.istio.io/inject: 'true'
        labels:
          sidecar.istio.io/inject: 'true'
