env: prod

hub: true

cluster:
  name: k8s
  domain: cluster.local

datacenter: dc1

region: yxl

desktops:
  - name: ubuntu-gpu
    image: kasmweb/ubuntu-noble-nvidia:dev
    tag: dev

    runtimeClassName: nvidia

    nodeSelector:
      nvidia.com/cuda.runtime.major: '12'

  - name: orcha-slicer
    image: lscr.io/linuxserver/orcaslicer
    tag: latest

    runtimeClassName: nvidia

    nodeSelector:
      nvidia.com/cuda.runtime.major: '12'

kasm:
  enabled: false